import audUsdIctTurtleSoupStrategy from "@strategy/aud_usd_ict_turtle_soup/strategy";
import audUsdNySweepBayesStrategy from "@strategy/aud_usd_ny_sweep_bayes/strategy";
import audUsdNySweepBayesPriorDayTargetStrategy from "@strategy/aud_usd_ny_sweep_bayes_prior_day_target/strategy";
import audUsdNySweepBayesPriorDayTargetOnCrudeOilFuturesStrategy from "@strategy/aud_usd_ny_sweep_bayes_prior_day_target_on_crude_oil_futures/strategy";
import audUsdNySweepBayesPriorDayTargetOnRussell2000FuturesStrategy from "@strategy/aud_usd_ny_sweep_bayes_prior_day_target_on_russell_2000_futures/strategy";
import audUsdNySweepLogitStrategy from "@strategy/aud_usd_ny_sweep_logit/strategy";
import audUsdNySweepLogitOnBritishPoundFuturesStrategy from "@strategy/aud_usd_ny_sweep_logit_on_british_pound_futures/strategy";
import audUsdNySweepLogitOnEuroFuturesStrategy from "@strategy/aud_usd_ny_sweep_logit_on_euro_futures/strategy";
import audUsdNySweepStumpStrategy from "@strategy/aud_usd_ny_sweep_stump/strategy";
import competitionAudNzdAsiaRangeLondonBreakoutSignalmonthBreakendminute360Breakstartminute180DirC8638be4Strategy from "@strategy/competition_aud_nzd_asia_range_london_breakout_signalmonth_breakendminute_360_breakstartminute_180_dir_c8638be4/strategy";
import competitionAudUsdNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarminute660Ming37fd5084Strategy from "@strategy/competition_aud_usd_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exitbarminute_660_ming_37fd5084/strategy";
import competitionAudUsdNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarminute660Ming5c432e4eStrategy from "@strategy/competition_aud_usd_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exitbarminute_660_ming_5c432e4e/strategy";
import competitionAudUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm38442616Strategy from "@strategy/competition_aud_usd_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_38442616/strategy";
import competitionAudUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm4767edd9Strategy from "@strategy/competition_aud_usd_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_4767edd9/strategy";
import competitionAudUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm850b714bStrategy from "@strategy/competition_aud_usd_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_850b714b/strategy";
import competitionAudUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmA3a7f703Strategy from "@strategy/competition_aud_usd_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_a3a7f703/strategy";
import competitionAudUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmC8c5223eStrategy from "@strategy/competition_aud_usd_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_c8c5223e/strategy";
import competitionAudUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmD5d237bfStrategy from "@strategy/competition_aud_usd_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_d5d237bf/strategy";
import competitionAustralianDollarFuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exit1aa4fa28Strategy from "@strategy/competition_australian_dollar_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exit_1aa4fa28/strategy";
import competitionAustralianDollarFuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570ExitA421c4edStrategy from "@strategy/competition_australian_dollar_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exit_a421c4ed/strategy";
import competitionAustralianDollarFuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570ExitDcd12f25Strategy from "@strategy/competition_australian_dollar_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exit_dcd12f25/strategy";
import competitionAustralianDollarFuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570ExitE08bc2a9Strategy from "@strategy/competition_australian_dollar_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exit_e08bc2a9/strategy";
import competitionAustralianDollarFuturesUsFirst30Last30ReversalSignalmonthDirectionOppositeEntrym77aa2b55Strategy from "@strategy/competition_australian_dollar_futures_us_first30_last30_reversal_signalmonth_direction_opposite_entrym_77aa2b55/strategy";
import competitionAustralianDollarFuturesUsFirst30Last30ReversalSignalmonthDirectionOppositeEntrymBbf594b5Strategy from "@strategy/competition_australian_dollar_futures_us_first30_last30_reversal_signalmonth_direction_opposite_entrym_bbf594b5/strategy";
import competitionCanadianDollarFuturesDailyTsmomNextOvernightSignalmonthDirectionMomentumEntryminEee85315Strategy from "@strategy/competition_canadian_dollar_futures_daily_tsmom_next_overnight_signalmonth_direction_momentum_entrymin_eee85315/strategy";
import competitionCanadianDollarFuturesOvernightCloseToOpenBiasSignalmonthEntryPriorRthCloseExi31e5e01aStrategy from "@strategy/competition_canadian_dollar_futures_overnight_close_to_open_bias_signalmonth_entry_prior_rth_close_exi_31e5e01a/strategy";
import competitionCrudeOilFuturesOvernightCloseToOpenBiasSignalmonthEntryPriorRthCloseExitNyO315d7644Strategy from "@strategy/competition_crude_oil_futures_overnight_close_to_open_bias_signalmonth_entry_prior_rth_close_exit_ny_o_315d7644/strategy";
import competitionDowJonesFuturesDailyTsmomNextOvernightSignalweekdaysideDirectionMomentumEntryminC2a8817bStrategy from "@strategy/competition_dow_jones_futures_daily_tsmom_next_overnight_signalweekdayside_direction_momentum_entrymin_c2a8817b/strategy";
import competitionDowJonesFuturesUsSecondlastLast30MomentumSignalweekdaysideDirectionSameEntryminuE49c2e15Strategy from "@strategy/competition_dow_jones_futures_us_secondlast_last30_momentum_signalweekdayside_direction_same_entryminu_e49c2e15/strategy";
import competitionEurCadDailyTsmomNextOvernightSignalmonthDirectionContrarianEntryminute945Exitmi2aad4569Strategy from "@strategy/competition_eur_cad_daily_tsmom_next_overnight_signalmonth_direction_contrarian_entryminute_945_exitmi_2aad4569/strategy";
import competitionEurCadDailyTsmomNextRthSignalweekdayDirectionContrarianEntryminute570ExitminuteA84ebf95Strategy from "@strategy/competition_eur_cad_daily_tsmom_next_rth_signalweekday_direction_contrarian_entryminute_570_exitminute_a84ebf95/strategy";
import competitionEurChfDailyTsmomNextRthSignalmonthDirectionMomentumEntryminute570Exitminute945391afa4aStrategy from "@strategy/competition_eur_chf_daily_tsmom_next_rth_signalmonth_direction_momentum_entryminute_570_exitminute_945_391afa4a/strategy";
import competitionEurGbpNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarminute945Ming724441efStrategy from "@strategy/competition_eur_gbp_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exitbarminute_945_ming_724441ef/strategy";
import competitionEurGbpNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarminute945Ming9f919a3dStrategy from "@strategy/competition_eur_gbp_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exitbarminute_945_ming_9f919a3d/strategy";
import competitionEurGbpUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm3c977a82Strategy from "@strategy/competition_eur_gbp_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_3c977a82/strategy";
import competitionEurJpyDailyTsmomNextRthSignalmonthDirectionMomentumEntryminute570Exitminute945563aa3f1Strategy from "@strategy/competition_eur_jpy_daily_tsmom_next_rth_signalmonth_direction_momentum_entryminute_570_exitminute_945_563aa3f1/strategy";
import competitionEurJpyDailyTsmomNextRthSignalweekdaysideDirectionMomentumEntryminute570ExitminuFc0fe405Strategy from "@strategy/competition_eur_jpy_daily_tsmom_next_rth_signalweekdayside_direction_momentum_entryminute_570_exitminu_fc0fe405/strategy";
import competitionEurJpyUsFirst30Last30MomentumSignalweekdaysideDirectionSameEntryminute930Exitba0a4a3f58Strategy from "@strategy/competition_eur_jpy_us_first30_last30_momentum_signalweekdayside_direction_same_entryminute_930_exitba_0a4a3f58/strategy";
import competitionEuroFuturesDailyTsmomNextRthSignalmonthDirectionContrarianEntryminute570Exitmin0b54da46Strategy from "@strategy/competition_euro_futures_daily_tsmom_next_rth_signalmonth_direction_contrarian_entryminute_570_exitmin_0b54da46/strategy";
import competitionGbpJpyDailyTsmomNextOvernightSignalmonthDirectionContrarianEntryminute945ExitmiAb520ea7Strategy from "@strategy/competition_gbp_jpy_daily_tsmom_next_overnight_signalmonth_direction_contrarian_entryminute_945_exitmi_ab520ea7/strategy";
import competitionGbpJpyDailyTsmomNextOvernightSignalweekdaysideDirectionMomentumEntryminute945Ex59f32062Strategy from "@strategy/competition_gbp_jpy_daily_tsmom_next_overnight_signalweekdayside_direction_momentum_entryminute_945_ex_59f32062/strategy";
import competitionGbpJpyLondonFirst30NyOpenReversalSignalmonthDirectionOppositeEntryminute480Exi3456ad91Strategy from "@strategy/competition_gbp_jpy_london_first30_ny_open_reversal_signalmonth_direction_opposite_entryminute_480_exi_3456ad91/strategy";
import competitionGbpJpyLondonFirst30NyOpenReversalSignalmonthDirectionOppositeEntryminute480ExiD549e3a7Strategy from "@strategy/competition_gbp_jpy_london_first30_ny_open_reversal_signalmonth_direction_opposite_entryminute_480_exi_d549e3a7/strategy";
import competitionGbpJpyLondonFirst30NyOpenReversalSignalweekdaysideDirectionOppositeEntryminute44eee8ecbStrategy from "@strategy/competition_gbp_jpy_london_first30_ny_open_reversal_signalweekdayside_direction_opposite_entryminute_4_4eee8ecb/strategy";
import competitionGbpJpyLondonFirst30NyOpenReversalSignalweekdaysideDirectionOppositeEntryminute45322bb1fStrategy from "@strategy/competition_gbp_jpy_london_first30_ny_open_reversal_signalweekdayside_direction_opposite_entryminute_4_5322bb1f/strategy";
import competitionGbpJpyLondonFirst30NyOpenReversalSignalweekdaysideDirectionOppositeEntryminute461184239Strategy from "@strategy/competition_gbp_jpy_london_first30_ny_open_reversal_signalweekdayside_direction_opposite_entryminute_4_61184239/strategy";
import competitionGbpJpyLondonFirst30NyOpenReversalSignalweekdaysideDirectionOppositeEntryminute480895cddStrategy from "@strategy/competition_gbp_jpy_london_first30_ny_open_reversal_signalweekdayside_direction_opposite_entryminute_4_80895cdd/strategy";
import competitionGbpJpyLondonFirst30NyOpenReversalSignalweekdaysideDirectionOppositeEntryminute4F28a94edStrategy from "@strategy/competition_gbp_jpy_london_first30_ny_open_reversal_signalweekdayside_direction_opposite_entryminute_4_f28a94ed/strategy";
import competitionGbpJpyNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarminute945Ming297a7a1dStrategy from "@strategy/competition_gbp_jpy_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exitbarminute_945_ming_297a7a1d/strategy";
import competitionGbpUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm030a5a73Strategy from "@strategy/competition_gbp_usd_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_030a5a73/strategy";
import competitionGbpUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm7a005ed0Strategy from "@strategy/competition_gbp_usd_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_7a005ed0/strategy";
import competitionGbpUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm9b2547fbStrategy from "@strategy/competition_gbp_usd_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_9b2547fb/strategy";
import competitionGbpUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmCa6667ecStrategy from "@strategy/competition_gbp_usd_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_ca6667ec/strategy";
import competitionGbpUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmDf7bf34bStrategy from "@strategy/competition_gbp_usd_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_df7bf34b/strategy";
import competitionGbpUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmE0e8d8deStrategy from "@strategy/competition_gbp_usd_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_e0e8d8de/strategy";
import competitionGoldFuturesDailyTsmomNextOvernightSignalweekdaysideDirectionMomentumEntryminute9C8e1caaeStrategy from "@strategy/competition_gold_futures_daily_tsmom_next_overnight_signalweekdayside_direction_momentum_entryminute_9_c8e1caae/strategy";
import competitionJapaneseYenFuturesUsFirst30Last30ReversalSignalweekdaysideDirectionOppositeEntry11a69e11Strategy from "@strategy/competition_japanese_yen_futures_us_first30_last30_reversal_signalweekdayside_direction_opposite_entry_11a69e11/strategy";
import competitionJapaneseYenFuturesUsFirst30Last30ReversalSignalweekdaysideDirectionOppositeEntry2b239b90Strategy from "@strategy/competition_japanese_yen_futures_us_first30_last30_reversal_signalweekdayside_direction_opposite_entry_2b239b90/strategy";
import competitionJapaneseYenFuturesUsFirst30Last30ReversalSignalweekdaysideDirectionOppositeEntryD778febbStrategy from "@strategy/competition_japanese_yen_futures_us_first30_last30_reversal_signalweekdayside_direction_opposite_entry_d778febb/strategy";
import competitionMicroBitcoinFuturesDailyTsmomNextOvernightSignalweekdaysideDirectionContrarianEn6003fc2dStrategy from "@strategy/competition_micro_bitcoin_futures_daily_tsmom_next_overnight_signalweekdayside_direction_contrarian_en_6003fc2d/strategy";
import competitionNewZealandDollarFuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exi1b75a7f7Strategy from "@strategy/competition_new_zealand_dollar_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exi_1b75a7f7/strategy";
import competitionNewZealandDollarFuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exi7ad85d81Strategy from "@strategy/competition_new_zealand_dollar_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exi_7ad85d81/strategy";
import competitionNewZealandDollarFuturesUsFirst30Last30ReversalSignalmonthDirectionOppositeEntry01defe06Strategy from "@strategy/competition_new_zealand_dollar_futures_us_first30_last30_reversal_signalmonth_direction_opposite_entry_01defe06/strategy";
import competitionNewZealandDollarFuturesUsFirst30Last30ReversalSignalmonthDirectionOppositeEntry4e0e379cStrategy from "@strategy/competition_new_zealand_dollar_futures_us_first30_last30_reversal_signalmonth_direction_opposite_entry_4e0e379c/strategy";
import competitionNewZealandDollarFuturesUsFirst30Last30ReversalSignalmonthDirectionOppositeEntry85b0ada6Strategy from "@strategy/competition_new_zealand_dollar_futures_us_first30_last30_reversal_signalmonth_direction_opposite_entry_85b0ada6/strategy";
import competitionNewZealandDollarFuturesUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryCb90e91cStrategy from "@strategy/competition_new_zealand_dollar_futures_us_first30_last30_reversal_signalmonth_direction_opposite_entry_cb90e91c/strategy";
import competitionNewZealandDollarFuturesUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryCe284576Strategy from "@strategy/competition_new_zealand_dollar_futures_us_first30_last30_reversal_signalmonth_direction_opposite_entry_ce284576/strategy";
import competitionNzdUsdDailyTsmomNextRthSignalmonthDirectionContrarianEntryminute570Exitminute9183b1d88Strategy from "@strategy/competition_nzd_usd_daily_tsmom_next_rth_signalmonth_direction_contrarian_entryminute_570_exitminute_9_183b1d88/strategy";
import competitionNzdUsdDailyTsmomNextRthSignalmonthDirectionContrarianEntryminute570Exitminute9Bf61d37cStrategy from "@strategy/competition_nzd_usd_daily_tsmom_next_rth_signalmonth_direction_contrarian_entryminute_570_exitminute_9_bf61d37c/strategy";
import competitionNzdUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmB9e9a661Strategy from "@strategy/competition_nzd_usd_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_b9e9a661/strategy";
import competitionRussell2000FuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarmi159713d0Strategy from "@strategy/competition_russell_2000_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exitbarmi_159713d0/strategy";
import competitionRussell2000FuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarmi5492f28aStrategy from "@strategy/competition_russell_2000_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exitbarmi_5492f28a/strategy";
import competitionRussell2000FuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarmi801e97d2Strategy from "@strategy/competition_russell_2000_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exitbarmi_801e97d2/strategy";
import competitionRussell2000FuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarmi879d00ecStrategy from "@strategy/competition_russell_2000_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exitbarmi_879d00ec/strategy";
import competitionSilverFuturesLondonFirst30NyOpenMomentumSignalweekdaysideDirectionSameEntryminut3b62ce88Strategy from "@strategy/competition_silver_futures_london_first30_ny_open_momentum_signalweekdayside_direction_same_entryminut_3b62ce88/strategy";
import competitionSilverFuturesLondonFirst30NyOpenMomentumSignalweekdaysideDirectionSameEntryminut5ce60b39Strategy from "@strategy/competition_silver_futures_london_first30_ny_open_momentum_signalweekdayside_direction_same_entryminut_5ce60b39/strategy";
import competitionSp500FuturesDailyTsmomNextOvernightSignalweekdaysideDirectionMomentumEntryminuteE3d4c85aStrategy from "@strategy/competition_sp_500_futures_daily_tsmom_next_overnight_signalweekdayside_direction_momentum_entryminute_e3d4c85a/strategy";
import competitionUsTreasury2yNoteFuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570ExD2289e05Strategy from "@strategy/competition_us_treasury_2y_note_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_ex_d2289e05/strategy";
import competitionUsTreasury2yNoteFuturesUsFirst30Last30MomentumSignalmonthDirectionSameEntrymin2439f151Strategy from "@strategy/competition_us_treasury_2y_note_futures_us_first30_last30_momentum_signalmonth_direction_same_entrymin_2439f151/strategy";
import competitionUsTreasury2yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn05a93122Strategy from "@strategy/competition_us_treasury_2y_note_futures_us_first30_last30_momentum_signalweekdayside_direction_same_en_05a93122/strategy";
import competitionUsTreasury2yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn28662e2dStrategy from "@strategy/competition_us_treasury_2y_note_futures_us_first30_last30_momentum_signalweekdayside_direction_same_en_28662e2d/strategy";
import competitionUsTreasury2yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn339e7451Strategy from "@strategy/competition_us_treasury_2y_note_futures_us_first30_last30_momentum_signalweekdayside_direction_same_en_339e7451/strategy";
import competitionUsTreasury2yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEnA966696eStrategy from "@strategy/competition_us_treasury_2y_note_futures_us_first30_last30_momentum_signalweekdayside_direction_same_en_a966696e/strategy";
import competitionUsTreasury30yBondFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEA80f2081Strategy from "@strategy/competition_us_treasury_30y_bond_futures_us_first30_last30_momentum_signalweekdayside_direction_same_e_a80f2081/strategy";
import competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalmonthDirectionSameEntrymin23a975e3Strategy from "@strategy/competition_us_treasury_5y_note_futures_us_first30_last30_momentum_signalmonth_direction_same_entrymin_23a975e3/strategy";
import competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn03688d86Strategy from "@strategy/competition_us_treasury_5y_note_futures_us_first30_last30_momentum_signalweekdayside_direction_same_en_03688d86/strategy";
import competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn1942c62bStrategy from "@strategy/competition_us_treasury_5y_note_futures_us_first30_last30_momentum_signalweekdayside_direction_same_en_1942c62b/strategy";
import competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn606cd362Strategy from "@strategy/competition_us_treasury_5y_note_futures_us_first30_last30_momentum_signalweekdayside_direction_same_en_606cd362/strategy";
import competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn62e3b6d2Strategy from "@strategy/competition_us_treasury_5y_note_futures_us_first30_last30_momentum_signalweekdayside_direction_same_en_62e3b6d2/strategy";
import competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn967bff3bStrategy from "@strategy/competition_us_treasury_5y_note_futures_us_first30_last30_momentum_signalweekdayside_direction_same_en_967bff3b/strategy";
import competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEnB7159e71Strategy from "@strategy/competition_us_treasury_5y_note_futures_us_first30_last30_momentum_signalweekdayside_direction_same_en_b7159e71/strategy";
import competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEnF66147aeStrategy from "@strategy/competition_us_treasury_5y_note_futures_us_first30_last30_momentum_signalweekdayside_direction_same_en_f66147ae/strategy";
import competitionUsdCadDailyTsmomNextOvernightSignalmonthDirectionMomentumEntryminute945ExitminuDca02dc1Strategy from "@strategy/competition_usd_cad_daily_tsmom_next_overnight_signalmonth_direction_momentum_entryminute_945_exitminu_dca02dc1/strategy";
import competitionUsdCadDailyTsmomNextOvernightSignalweekdayDirectionContrarianEntryminute945ExitEd793acaStrategy from "@strategy/competition_usd_cad_daily_tsmom_next_overnight_signalweekday_direction_contrarian_entryminute_945_exit_ed793aca/strategy";
import competitionUsdCadUsFirst30Last30MomentumSignalmonthDirectionSameEntryminute930Exitbarminut087745e1Strategy from "@strategy/competition_usd_cad_us_first30_last30_momentum_signalmonth_direction_same_entryminute_930_exitbarminut_087745e1/strategy";
import competitionUsdCadUsFirst30Last30MomentumSignalmonthDirectionSameEntryminute930Exitbarminut234db7bfStrategy from "@strategy/competition_usd_cad_us_first30_last30_momentum_signalmonth_direction_same_entryminute_930_exitbarminut_234db7bf/strategy";
import competitionUsdCadUsFirst30Last30MomentumSignalmonthDirectionSameEntryminute930Exitbarminut9b58c643Strategy from "@strategy/competition_usd_cad_us_first30_last30_momentum_signalmonth_direction_same_entryminute_930_exitbarminut_9b58c643/strategy";
import competitionUsdCadUsFirst30Last30MomentumSignalmonthDirectionSameEntryminute930ExitbarminutA2ced8d9Strategy from "@strategy/competition_usd_cad_us_first30_last30_momentum_signalmonth_direction_same_entryminute_930_exitbarminut_a2ced8d9/strategy";
import competitionUsdCadUsFirst30Last30MomentumSignalmonthDirectionSameEntryminute930ExitbarminutC1317995Strategy from "@strategy/competition_usd_cad_us_first30_last30_momentum_signalmonth_direction_same_entryminute_930_exitbarminut_c1317995/strategy";
import competitionUsdCadUsFirst30Last30MomentumSignalmonthDirectionSameEntryminute930ExitbarminutD4e896a1Strategy from "@strategy/competition_usd_cad_us_first30_last30_momentum_signalmonth_direction_same_entryminute_930_exitbarminut_d4e896a1/strategy";
import competitionUsdCadUsFirst30Last30MomentumSignalweekdaysideDirectionSameEntryminute930Exitba4c0f04b8Strategy from "@strategy/competition_usd_cad_us_first30_last30_momentum_signalweekdayside_direction_same_entryminute_930_exitba_4c0f04b8/strategy";
import competitionUsdCadUsFirst30Last30MomentumSignalweekdaysideDirectionSameEntryminute930ExitbaBaf00d24Strategy from "@strategy/competition_usd_cad_us_first30_last30_momentum_signalweekdayside_direction_same_entryminute_930_exitba_baf00d24/strategy";
import competitionUsdChfDailyTsmomNextRthSignalweekdayDirectionMomentumEntryminute570Exitminute9F3f4b076Strategy from "@strategy/competition_usd_chf_daily_tsmom_next_rth_signalweekday_direction_momentum_entryminute_570_exitminute_9_f3f4b076/strategy";
import competitionUsdChfOvernightCloseToOpenBiasSignalmonthEntryPriorRthCloseExitNyOpenSideSB92958d0Strategy from "@strategy/competition_usd_chf_overnight_close_to_open_bias_signalmonth_entry_prior_rth_close_exit_ny_open_side_s_b92958d0/strategy";
import competitionUsdJpyAsiaRangeLondonBreakoutSignalweekdaysideBreakendminute360Breakstartminute15a0c1124Strategy from "@strategy/competition_usd_jpy_asia_range_london_breakout_signalweekdayside_breakendminute_360_breakstartminute_1_5a0c1124/strategy";
import competitionUsdJpyAsiaRangeLondonBreakoutSignalweekdaysideBreakendminute360Breakstartminute183470b07Strategy from "@strategy/competition_usd_jpy_asia_range_london_breakout_signalweekdayside_breakendminute_360_breakstartminute_1_83470b07/strategy";
import competitionUsdJpyAsiaRangeLondonBreakoutSignalweekdaysideBreakendminute360Breakstartminute1Fca40701Strategy from "@strategy/competition_usd_jpy_asia_range_london_breakout_signalweekdayside_breakendminute_360_breakstartminute_1_fca40701/strategy";
import competitionUsdJpyLondonFirst30NyOpenMomentumSignalmonthDirectionSameEntryminute480Exitbar3d256058Strategy from "@strategy/competition_usd_jpy_london_first30_ny_open_momentum_signalmonth_direction_same_entryminute_480_exitbar_3d256058/strategy";
import competitionUsdJpyLondonFirst30NyOpenMomentumSignalmonthDirectionSameEntryminute480Exitbar77986608Strategy from "@strategy/competition_usd_jpy_london_first30_ny_open_momentum_signalmonth_direction_same_entryminute_480_exitbar_77986608/strategy";
import competitionUsdJpyLondonFirst30NyOpenMomentumSignalmonthDirectionSameEntryminute480Exitbar79315567Strategy from "@strategy/competition_usd_jpy_london_first30_ny_open_momentum_signalmonth_direction_same_entryminute_480_exitbar_79315567/strategy";
import competitionUsdJpyLondonFirst30NyOpenMomentumSignalmonthDirectionSameEntryminute480ExitbarC09e63b8Strategy from "@strategy/competition_usd_jpy_london_first30_ny_open_momentum_signalmonth_direction_same_entryminute_480_exitbar_c09e63b8/strategy";
import competitionUsdJpyLondonFirst30NyOpenMomentumSignalweekdaysideDirectionSameEntryminute480ECe191581Strategy from "@strategy/competition_usd_jpy_london_first30_ny_open_momentum_signalweekdayside_direction_same_entryminute_480_e_ce191581/strategy";
import competitionUsdJpyLondonFirst30NyOpenMomentumSignalweekdaysideDirectionSameEntryminute480ED78525d6Strategy from "@strategy/competition_usd_jpy_london_first30_ny_open_momentum_signalweekdayside_direction_same_entryminute_480_e_d78525d6/strategy";
import competitionUsdJpyUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm4d0f0235Strategy from "@strategy/competition_usd_jpy_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_4d0f0235/strategy";
import competitionUsdJpyUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm6403ee92Strategy from "@strategy/competition_usd_jpy_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_6403ee92/strategy";
import competitionUsdJpyUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmA4388977Strategy from "@strategy/competition_usd_jpy_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_a4388977/strategy";
import competitionUsdJpyUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmAe2dcda5Strategy from "@strategy/competition_usd_jpy_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_ae2dcda5/strategy";
import competitionUsdJpyUsFirst30Last30ReversalSignalweekdaysideDirectionOppositeEntryminute930Ex40e6d9aeStrategy from "@strategy/competition_usd_jpy_us_first30_last30_reversal_signalweekdayside_direction_opposite_entryminute_930_ex_40e6d9ae/strategy";
import competitionUsdJpyUsFirst30Last30ReversalSignalweekdaysideDirectionOppositeEntryminute930Ex8fc27c9bStrategy from "@strategy/competition_usd_jpy_us_first30_last30_reversal_signalweekdayside_direction_opposite_entryminute_930_ex_8fc27c9b/strategy";
import copperFuturesRedditCapitulationReversionStrategy from "@strategy/copper_futures_reddit_capitulation_reversion/strategy";
import copperFuturesRedditOrbBreakoutOppositeStrategy from "@strategy/copper_futures_reddit_orb_breakout_opposite/strategy";
import copperFuturesToriTradesTrendlineBreakRetestStrategy from "@strategy/copper_futures_tori_trades_trendline_break_retest/strategy";
import crudeOilFuturesIctSweepFvgStrategy from "@strategy/crude_oil_futures_ict_sweep_fvg/strategy";
import crudeOilFuturesMomentumStrategy from "@strategy/crude_oil_futures_momentum/strategy";
import crudeOilFuturesRedditOrbBreakoutStrategy from "@strategy/crude_oil_futures_reddit_orb_breakout/strategy";
import crudeOilFuturesToriTradesTrendlineBreakRetestStrategy from "@strategy/crude_oil_futures_tori_trades_trendline_break_retest/strategy";
import dowJonesFuturesRedditCapitulationReversionStrategy from "@strategy/dow_jones_futures_reddit_capitulation_reversion/strategy";
import dowJonesFuturesRedditCapitulationReversionOnUsdChfStrategy from "@strategy/dow_jones_futures_reddit_capitulation_reversion_on_usd_chf/strategy";
import dowJonesFuturesRedditEmaPullbackStrategy from "@strategy/dow_jones_futures_reddit_ema_pullback/strategy";
import dowJonesFuturesRedditOrbBreakoutOppositeStrategy from "@strategy/dow_jones_futures_reddit_orb_breakout_opposite/strategy";
import dowJonesFuturesRedditOrbRetestStrategy from "@strategy/dow_jones_futures_reddit_orb_retest/strategy";
import eurUsdHumbledTraderVwapPullbackStrategy from "@strategy/eur_usd_humbled_trader_vwap_pullback/strategy";
import eurUsdNySweepBayesStrategy from "@strategy/eur_usd_ny_sweep_bayes/strategy";
import eurUsdNySweepLogitStrategy from "@strategy/eur_usd_ny_sweep_logit/strategy";
import eurUsdNySweepLogitOnBritishPoundFuturesStrategy from "@strategy/eur_usd_ny_sweep_logit_on_british_pound_futures/strategy";
import eurUsdNySweepLogitOnEuroFuturesStrategy from "@strategy/eur_usd_ny_sweep_logit_on_euro_futures/strategy";
import eurUsdNySweepStumpStrategy from "@strategy/eur_usd_ny_sweep_stump/strategy";
import eurUsdNySweepStumpPriorDayTargetStrategy from "@strategy/eur_usd_ny_sweep_stump_prior_day_target/strategy";
import eurUsdNySweepStumpPriorDayTargetOnSilverFuturesOppositeStrategy from "@strategy/eur_usd_ny_sweep_stump_prior_day_target_on_silver_futures_opposite/strategy";
import gbpUsdHumbledTraderVwapPullbackStrategy from "@strategy/gbp_usd_humbled_trader_vwap_pullback/strategy";
import gbpUsdIctTurtleSoupStrategy from "@strategy/gbp_usd_ict_turtle_soup/strategy";
import gbpUsdMeanReversionStrategy from "@strategy/gbp_usd_mean_reversion/strategy";
import gbpUsdNySweepBayesStrategy from "@strategy/gbp_usd_ny_sweep_bayes/strategy";
import gbpUsdNySweepBayesOnNewZealandDollarFuturesStrategy from "@strategy/gbp_usd_ny_sweep_bayes_on_new_zealand_dollar_futures/strategy";
import gbpUsdNySweepBayesPriorDayTargetOnSp500FuturesStrategy from "@strategy/gbp_usd_ny_sweep_bayes_prior_day_target_on_sp_500_futures/strategy";
import gbpUsdNySweepLogitStrategy from "@strategy/gbp_usd_ny_sweep_logit/strategy";
import gbpUsdNySweepStumpStrategy from "@strategy/gbp_usd_ny_sweep_stump/strategy";
import gbpUsdNySweepStumpOnBritishPoundFuturesStrategy from "@strategy/gbp_usd_ny_sweep_stump_on_british_pound_futures/strategy";
import gbpUsdNySweepStumpOnEuroFuturesStrategy from "@strategy/gbp_usd_ny_sweep_stump_on_euro_futures/strategy";
import goldFuturesEchoNeuralMeanReversionStrategy from "@strategy/gold_futures_echo_neural_mean_reversion/strategy";
import goldFuturesEchoNeuralMeanReversionBalancedStrategy from "@strategy/gold_futures_echo_neural_mean_reversion_balanced/strategy";
import goldFuturesEchoNeuralMomentumStrategy from "@strategy/gold_futures_echo_neural_momentum/strategy";
import goldFuturesEchoNeuralMomentumBalancedStrategy from "@strategy/gold_futures_echo_neural_momentum_balanced/strategy";
import goldFuturesHumbledTraderVwapPullbackOppositeStrategy from "@strategy/gold_futures_humbled_trader_vwap_pullback_opposite/strategy";
import goldFuturesIctSweepFvgStrategy from "@strategy/gold_futures_ict_sweep_fvg/strategy";
import goldFuturesRedditEmaPullbackStrategy from "@strategy/gold_futures_reddit_ema_pullback/strategy";
import goldFuturesRedditOrbBreakoutStrategy from "@strategy/gold_futures_reddit_orb_breakout/strategy";
import goldFuturesToriTradesTrendlineBreakRetestStrategy from "@strategy/gold_futures_tori_trades_trendline_break_retest/strategy";
import goldFuturesToriTradesTrendlineBreakRetestOnAudNzdOppositeStrategy from "@strategy/gold_futures_tori_trades_trendline_break_retest_on_aud_nzd_opposite/strategy";
import goldFuturesToriTradesTrendlineBreakRetestOnEurCadStrategy from "@strategy/gold_futures_tori_trades_trendline_break_retest_on_eur_cad/strategy";
import goldFuturesToriTradesTrendlineBreakRetestOnUsdCadOppositeStrategy from "@strategy/gold_futures_tori_trades_trendline_break_retest_on_usd_cad_opposite/strategy";
import goldFuturesToriTradesTrendlineBreakRetestOnUsdJpyStrategy from "@strategy/gold_futures_tori_trades_trendline_break_retest_on_usd_jpy/strategy";
import goldSpotEchoNeuralMeanReversionStrategy from "@strategy/gold_spot_echo_neural_mean_reversion/strategy";
import goldSpotEchoNeuralMeanReversionBalancedStrategy from "@strategy/gold_spot_echo_neural_mean_reversion_balanced/strategy";
import goldSpotEchoNeuralMomentumStrategy from "@strategy/gold_spot_echo_neural_momentum/strategy";
import goldSpotEchoNeuralMomentumBalancedStrategy from "@strategy/gold_spot_echo_neural_momentum_balanced/strategy";
import goldSpotToriTradesTrendlineBreakRetestStrategy from "@strategy/gold_spot_tori_trades_trendline_break_retest/strategy";
import nasdaq100FuturesClaytraderSupportResistanceRetestStrategy from "@strategy/nasdaq_100_futures_claytrader_support_resistance_retest/strategy";
import nasdaq100FuturesDecileForwardEdge5mStrategy from "@strategy/nasdaq_100_futures_decile_forward_edge_5m/strategy";
import nasdaq100FuturesMomentumStrategy from "@strategy/nasdaq_100_futures_momentum/strategy";
import nasdaq100FuturesPercentileRangeStudy15mStrategy from "@strategy/nasdaq_100_futures_percentile_range_study_15m/strategy";
import nasdaq100FuturesPercentileRangeStudy1hStrategy from "@strategy/nasdaq_100_futures_percentile_range_study_1h/strategy";
import nasdaq100FuturesPercentileRangeStudy1mStrategy from "@strategy/nasdaq_100_futures_percentile_range_study_1m/strategy";
import nasdaq100FuturesPercentileRangeStudy30mStrategy from "@strategy/nasdaq_100_futures_percentile_range_study_30m/strategy";
import nasdaq100FuturesPercentileRangeStudy5mStrategy from "@strategy/nasdaq_100_futures_percentile_range_study_5m/strategy";
import nasdaq100FuturesRedditEmaPullbackStrategy from "@strategy/nasdaq_100_futures_reddit_ema_pullback/strategy";
import nasdaq100FuturesRedditOrbBreakoutStrategy from "@strategy/nasdaq_100_futures_reddit_orb_breakout/strategy";
import nasdaq100FuturesRedditOrbRetestStrategy from "@strategy/nasdaq_100_futures_reddit_orb_retest/strategy";
import nasdaq100FuturesRoundHundredRejection15mStrategy from "@strategy/nasdaq_100_futures_round_hundred_rejection_15m/strategy";
import nasdaq100FuturesSma20SupportBounce1hStrategy from "@strategy/nasdaq_100_futures_sma20_support_bounce_1h/strategy";
import nasdaq100FuturesSma50Sma200Cross15mStrategy from "@strategy/nasdaq_100_futures_sma50_sma200_cross_15m/strategy";
import nasdaq100FuturesToriTradesTrendlineBreakRetestStrategy from "@strategy/nasdaq_100_futures_tori_trades_trendline_break_retest/strategy";
import nzdUsdNySweepBayesStrategy from "@strategy/nzd_usd_ny_sweep_bayes/strategy";
import nzdUsdNySweepLogitStrategy from "@strategy/nzd_usd_ny_sweep_logit/strategy";
import nzdUsdNySweepStumpStrategy from "@strategy/nzd_usd_ny_sweep_stump/strategy";
import russell2000FuturesClaytraderSupportResistanceRetestStrategy from "@strategy/russell_2000_futures_claytrader_support_resistance_retest/strategy";
import russell2000FuturesIctSweepFvgStrategy from "@strategy/russell_2000_futures_ict_sweep_fvg/strategy";
import russell2000FuturesRedditOrbRetestStrategy from "@strategy/russell_2000_futures_reddit_orb_retest/strategy";
import silverFuturesRedditCapitulationReversionStrategy from "@strategy/silver_futures_reddit_capitulation_reversion/strategy";
import sp500FuturesRedditOrbBreakoutStrategy from "@strategy/sp_500_futures_reddit_orb_breakout/strategy";
import sp500FuturesToriTradesTrendlineBreakRetestStrategy from "@strategy/sp_500_futures_tori_trades_trendline_break_retest/strategy";
import usTreasury10yNoteFuturesMomentumOppositeStrategy from "@strategy/us_treasury_10y_note_futures_momentum_opposite/strategy";
import usdCadNySweepBayesStrategy from "@strategy/usd_cad_ny_sweep_bayes/strategy";
import usdCadNySweepLogitStrategy from "@strategy/usd_cad_ny_sweep_logit/strategy";
import usdCadNySweepLogitPriorDayTargetStrategy from "@strategy/usd_cad_ny_sweep_logit_prior_day_target/strategy";
import usdCadNySweepLogitPriorDayTargetOnCanadianDollarFuturesOppositeStrategy from "@strategy/usd_cad_ny_sweep_logit_prior_day_target_on_canadian_dollar_futures_opposite/strategy";
import usdCadNySweepStumpStrategy from "@strategy/usd_cad_ny_sweep_stump/strategy";
import usdChfNySweepStumpStrategy from "@strategy/usd_chf_ny_sweep_stump/strategy";
import usdJpyNySweepBayesStrategy from "@strategy/usd_jpy_ny_sweep_bayes/strategy";
import usdJpyNySweepBayesOnCopperFuturesStrategy from "@strategy/usd_jpy_ny_sweep_bayes_on_copper_futures/strategy";
import usdJpyNySweepBayesOnDowJonesFuturesStrategy from "@strategy/usd_jpy_ny_sweep_bayes_on_dow_jones_futures/strategy";
import usdJpyNySweepLogitStrategy from "@strategy/usd_jpy_ny_sweep_logit/strategy";
import usdJpyNySweepLogitOnSp500FuturesStrategy from "@strategy/usd_jpy_ny_sweep_logit_on_sp_500_futures/strategy";
import usdJpyNySweepStumpStrategy from "@strategy/usd_jpy_ny_sweep_stump/strategy";
import usdJpyNySweepStumpOnCopperFuturesStrategy from "@strategy/usd_jpy_ny_sweep_stump_on_copper_futures/strategy";
import usdJpyNySweepStumpPriorDayTargetStrategy from "@strategy/usd_jpy_ny_sweep_stump_prior_day_target/strategy";
import usdJpyNySweepStumpPriorDayTargetOnNaturalGasFuturesOppositeStrategy from "@strategy/usd_jpy_ny_sweep_stump_prior_day_target_on_natural_gas_futures_opposite/strategy";

import type { StrategyDefinition } from "@/lib/strategy-definition";

export type { StrategyDefinition, StrategySignal } from "@/lib/strategy-definition";

export const STRATEGY_DEFINITIONS: StrategyDefinition[] = [
  audUsdIctTurtleSoupStrategy,
  audUsdNySweepBayesStrategy,
  audUsdNySweepBayesPriorDayTargetStrategy,
  audUsdNySweepBayesPriorDayTargetOnCrudeOilFuturesStrategy,
  audUsdNySweepBayesPriorDayTargetOnRussell2000FuturesStrategy,
  audUsdNySweepLogitStrategy,
  audUsdNySweepLogitOnBritishPoundFuturesStrategy,
  audUsdNySweepLogitOnEuroFuturesStrategy,
  audUsdNySweepStumpStrategy,
  competitionAudNzdAsiaRangeLondonBreakoutSignalmonthBreakendminute360Breakstartminute180DirC8638be4Strategy,
  competitionAudUsdNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarminute660Ming37fd5084Strategy,
  competitionAudUsdNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarminute660Ming5c432e4eStrategy,
  competitionAudUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm38442616Strategy,
  competitionAudUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm4767edd9Strategy,
  competitionAudUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm850b714bStrategy,
  competitionAudUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmA3a7f703Strategy,
  competitionAudUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmC8c5223eStrategy,
  competitionAudUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmD5d237bfStrategy,
  competitionAustralianDollarFuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exit1aa4fa28Strategy,
  competitionAustralianDollarFuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570ExitA421c4edStrategy,
  competitionAustralianDollarFuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570ExitDcd12f25Strategy,
  competitionAustralianDollarFuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570ExitE08bc2a9Strategy,
  competitionAustralianDollarFuturesUsFirst30Last30ReversalSignalmonthDirectionOppositeEntrym77aa2b55Strategy,
  competitionAustralianDollarFuturesUsFirst30Last30ReversalSignalmonthDirectionOppositeEntrymBbf594b5Strategy,
  competitionCanadianDollarFuturesDailyTsmomNextOvernightSignalmonthDirectionMomentumEntryminEee85315Strategy,
  competitionCanadianDollarFuturesOvernightCloseToOpenBiasSignalmonthEntryPriorRthCloseExi31e5e01aStrategy,
  competitionCrudeOilFuturesOvernightCloseToOpenBiasSignalmonthEntryPriorRthCloseExitNyO315d7644Strategy,
  competitionDowJonesFuturesDailyTsmomNextOvernightSignalweekdaysideDirectionMomentumEntryminC2a8817bStrategy,
  competitionDowJonesFuturesUsSecondlastLast30MomentumSignalweekdaysideDirectionSameEntryminuE49c2e15Strategy,
  competitionEurCadDailyTsmomNextOvernightSignalmonthDirectionContrarianEntryminute945Exitmi2aad4569Strategy,
  competitionEurCadDailyTsmomNextRthSignalweekdayDirectionContrarianEntryminute570ExitminuteA84ebf95Strategy,
  competitionEurChfDailyTsmomNextRthSignalmonthDirectionMomentumEntryminute570Exitminute945391afa4aStrategy,
  competitionEurGbpNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarminute945Ming724441efStrategy,
  competitionEurGbpNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarminute945Ming9f919a3dStrategy,
  competitionEurGbpUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm3c977a82Strategy,
  competitionEurJpyDailyTsmomNextRthSignalmonthDirectionMomentumEntryminute570Exitminute945563aa3f1Strategy,
  competitionEurJpyDailyTsmomNextRthSignalweekdaysideDirectionMomentumEntryminute570ExitminuFc0fe405Strategy,
  competitionEurJpyUsFirst30Last30MomentumSignalweekdaysideDirectionSameEntryminute930Exitba0a4a3f58Strategy,
  competitionEuroFuturesDailyTsmomNextRthSignalmonthDirectionContrarianEntryminute570Exitmin0b54da46Strategy,
  competitionGbpJpyDailyTsmomNextOvernightSignalmonthDirectionContrarianEntryminute945ExitmiAb520ea7Strategy,
  competitionGbpJpyDailyTsmomNextOvernightSignalweekdaysideDirectionMomentumEntryminute945Ex59f32062Strategy,
  competitionGbpJpyLondonFirst30NyOpenReversalSignalmonthDirectionOppositeEntryminute480Exi3456ad91Strategy,
  competitionGbpJpyLondonFirst30NyOpenReversalSignalmonthDirectionOppositeEntryminute480ExiD549e3a7Strategy,
  competitionGbpJpyLondonFirst30NyOpenReversalSignalweekdaysideDirectionOppositeEntryminute44eee8ecbStrategy,
  competitionGbpJpyLondonFirst30NyOpenReversalSignalweekdaysideDirectionOppositeEntryminute45322bb1fStrategy,
  competitionGbpJpyLondonFirst30NyOpenReversalSignalweekdaysideDirectionOppositeEntryminute461184239Strategy,
  competitionGbpJpyLondonFirst30NyOpenReversalSignalweekdaysideDirectionOppositeEntryminute480895cddStrategy,
  competitionGbpJpyLondonFirst30NyOpenReversalSignalweekdaysideDirectionOppositeEntryminute4F28a94edStrategy,
  competitionGbpJpyNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarminute945Ming297a7a1dStrategy,
  competitionGbpUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm030a5a73Strategy,
  competitionGbpUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm7a005ed0Strategy,
  competitionGbpUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm9b2547fbStrategy,
  competitionGbpUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmCa6667ecStrategy,
  competitionGbpUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmDf7bf34bStrategy,
  competitionGbpUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmE0e8d8deStrategy,
  competitionGoldFuturesDailyTsmomNextOvernightSignalweekdaysideDirectionMomentumEntryminute9C8e1caaeStrategy,
  competitionJapaneseYenFuturesUsFirst30Last30ReversalSignalweekdaysideDirectionOppositeEntry11a69e11Strategy,
  competitionJapaneseYenFuturesUsFirst30Last30ReversalSignalweekdaysideDirectionOppositeEntry2b239b90Strategy,
  competitionJapaneseYenFuturesUsFirst30Last30ReversalSignalweekdaysideDirectionOppositeEntryD778febbStrategy,
  competitionMicroBitcoinFuturesDailyTsmomNextOvernightSignalweekdaysideDirectionContrarianEn6003fc2dStrategy,
  competitionNewZealandDollarFuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exi1b75a7f7Strategy,
  competitionNewZealandDollarFuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exi7ad85d81Strategy,
  competitionNewZealandDollarFuturesUsFirst30Last30ReversalSignalmonthDirectionOppositeEntry01defe06Strategy,
  competitionNewZealandDollarFuturesUsFirst30Last30ReversalSignalmonthDirectionOppositeEntry4e0e379cStrategy,
  competitionNewZealandDollarFuturesUsFirst30Last30ReversalSignalmonthDirectionOppositeEntry85b0ada6Strategy,
  competitionNewZealandDollarFuturesUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryCb90e91cStrategy,
  competitionNewZealandDollarFuturesUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryCe284576Strategy,
  competitionNzdUsdDailyTsmomNextRthSignalmonthDirectionContrarianEntryminute570Exitminute9183b1d88Strategy,
  competitionNzdUsdDailyTsmomNextRthSignalmonthDirectionContrarianEntryminute570Exitminute9Bf61d37cStrategy,
  competitionNzdUsdUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmB9e9a661Strategy,
  competitionRussell2000FuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarmi159713d0Strategy,
  competitionRussell2000FuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarmi5492f28aStrategy,
  competitionRussell2000FuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarmi801e97d2Strategy,
  competitionRussell2000FuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570Exitbarmi879d00ecStrategy,
  competitionSilverFuturesLondonFirst30NyOpenMomentumSignalweekdaysideDirectionSameEntryminut3b62ce88Strategy,
  competitionSilverFuturesLondonFirst30NyOpenMomentumSignalweekdaysideDirectionSameEntryminut5ce60b39Strategy,
  competitionSp500FuturesDailyTsmomNextOvernightSignalweekdaysideDirectionMomentumEntryminuteE3d4c85aStrategy,
  competitionUsTreasury2yNoteFuturesNyOpenGapFadeSignalmonthDirectionFadeEntryminute570ExD2289e05Strategy,
  competitionUsTreasury2yNoteFuturesUsFirst30Last30MomentumSignalmonthDirectionSameEntrymin2439f151Strategy,
  competitionUsTreasury2yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn05a93122Strategy,
  competitionUsTreasury2yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn28662e2dStrategy,
  competitionUsTreasury2yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn339e7451Strategy,
  competitionUsTreasury2yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEnA966696eStrategy,
  competitionUsTreasury30yBondFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEA80f2081Strategy,
  competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalmonthDirectionSameEntrymin23a975e3Strategy,
  competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn03688d86Strategy,
  competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn1942c62bStrategy,
  competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn606cd362Strategy,
  competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn62e3b6d2Strategy,
  competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEn967bff3bStrategy,
  competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEnB7159e71Strategy,
  competitionUsTreasury5yNoteFuturesUsFirst30Last30MomentumSignalweekdaysideDirectionSameEnF66147aeStrategy,
  competitionUsdCadDailyTsmomNextOvernightSignalmonthDirectionMomentumEntryminute945ExitminuDca02dc1Strategy,
  competitionUsdCadDailyTsmomNextOvernightSignalweekdayDirectionContrarianEntryminute945ExitEd793acaStrategy,
  competitionUsdCadUsFirst30Last30MomentumSignalmonthDirectionSameEntryminute930Exitbarminut087745e1Strategy,
  competitionUsdCadUsFirst30Last30MomentumSignalmonthDirectionSameEntryminute930Exitbarminut234db7bfStrategy,
  competitionUsdCadUsFirst30Last30MomentumSignalmonthDirectionSameEntryminute930Exitbarminut9b58c643Strategy,
  competitionUsdCadUsFirst30Last30MomentumSignalmonthDirectionSameEntryminute930ExitbarminutA2ced8d9Strategy,
  competitionUsdCadUsFirst30Last30MomentumSignalmonthDirectionSameEntryminute930ExitbarminutC1317995Strategy,
  competitionUsdCadUsFirst30Last30MomentumSignalmonthDirectionSameEntryminute930ExitbarminutD4e896a1Strategy,
  competitionUsdCadUsFirst30Last30MomentumSignalweekdaysideDirectionSameEntryminute930Exitba4c0f04b8Strategy,
  competitionUsdCadUsFirst30Last30MomentumSignalweekdaysideDirectionSameEntryminute930ExitbaBaf00d24Strategy,
  competitionUsdChfDailyTsmomNextRthSignalweekdayDirectionMomentumEntryminute570Exitminute9F3f4b076Strategy,
  competitionUsdChfOvernightCloseToOpenBiasSignalmonthEntryPriorRthCloseExitNyOpenSideSB92958d0Strategy,
  competitionUsdJpyAsiaRangeLondonBreakoutSignalweekdaysideBreakendminute360Breakstartminute15a0c1124Strategy,
  competitionUsdJpyAsiaRangeLondonBreakoutSignalweekdaysideBreakendminute360Breakstartminute183470b07Strategy,
  competitionUsdJpyAsiaRangeLondonBreakoutSignalweekdaysideBreakendminute360Breakstartminute1Fca40701Strategy,
  competitionUsdJpyLondonFirst30NyOpenMomentumSignalmonthDirectionSameEntryminute480Exitbar3d256058Strategy,
  competitionUsdJpyLondonFirst30NyOpenMomentumSignalmonthDirectionSameEntryminute480Exitbar77986608Strategy,
  competitionUsdJpyLondonFirst30NyOpenMomentumSignalmonthDirectionSameEntryminute480Exitbar79315567Strategy,
  competitionUsdJpyLondonFirst30NyOpenMomentumSignalmonthDirectionSameEntryminute480ExitbarC09e63b8Strategy,
  competitionUsdJpyLondonFirst30NyOpenMomentumSignalweekdaysideDirectionSameEntryminute480ECe191581Strategy,
  competitionUsdJpyLondonFirst30NyOpenMomentumSignalweekdaysideDirectionSameEntryminute480ED78525d6Strategy,
  competitionUsdJpyUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm4d0f0235Strategy,
  competitionUsdJpyUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930Exitbarm6403ee92Strategy,
  competitionUsdJpyUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmA4388977Strategy,
  competitionUsdJpyUsFirst30Last30ReversalSignalmonthDirectionOppositeEntryminute930ExitbarmAe2dcda5Strategy,
  competitionUsdJpyUsFirst30Last30ReversalSignalweekdaysideDirectionOppositeEntryminute930Ex40e6d9aeStrategy,
  competitionUsdJpyUsFirst30Last30ReversalSignalweekdaysideDirectionOppositeEntryminute930Ex8fc27c9bStrategy,
  copperFuturesRedditCapitulationReversionStrategy,
  copperFuturesRedditOrbBreakoutOppositeStrategy,
  copperFuturesToriTradesTrendlineBreakRetestStrategy,
  crudeOilFuturesIctSweepFvgStrategy,
  crudeOilFuturesMomentumStrategy,
  crudeOilFuturesRedditOrbBreakoutStrategy,
  crudeOilFuturesToriTradesTrendlineBreakRetestStrategy,
  dowJonesFuturesRedditCapitulationReversionStrategy,
  dowJonesFuturesRedditCapitulationReversionOnUsdChfStrategy,
  dowJonesFuturesRedditEmaPullbackStrategy,
  dowJonesFuturesRedditOrbBreakoutOppositeStrategy,
  dowJonesFuturesRedditOrbRetestStrategy,
  eurUsdHumbledTraderVwapPullbackStrategy,
  eurUsdNySweepBayesStrategy,
  eurUsdNySweepLogitStrategy,
  eurUsdNySweepLogitOnBritishPoundFuturesStrategy,
  eurUsdNySweepLogitOnEuroFuturesStrategy,
  eurUsdNySweepStumpStrategy,
  eurUsdNySweepStumpPriorDayTargetStrategy,
  eurUsdNySweepStumpPriorDayTargetOnSilverFuturesOppositeStrategy,
  gbpUsdHumbledTraderVwapPullbackStrategy,
  gbpUsdIctTurtleSoupStrategy,
  gbpUsdMeanReversionStrategy,
  gbpUsdNySweepBayesStrategy,
  gbpUsdNySweepBayesOnNewZealandDollarFuturesStrategy,
  gbpUsdNySweepBayesPriorDayTargetOnSp500FuturesStrategy,
  gbpUsdNySweepLogitStrategy,
  gbpUsdNySweepStumpStrategy,
  gbpUsdNySweepStumpOnBritishPoundFuturesStrategy,
  gbpUsdNySweepStumpOnEuroFuturesStrategy,
  goldFuturesEchoNeuralMeanReversionStrategy,
  goldFuturesEchoNeuralMeanReversionBalancedStrategy,
  goldFuturesEchoNeuralMomentumStrategy,
  goldFuturesEchoNeuralMomentumBalancedStrategy,
  goldFuturesHumbledTraderVwapPullbackOppositeStrategy,
  goldFuturesIctSweepFvgStrategy,
  goldFuturesRedditEmaPullbackStrategy,
  goldFuturesRedditOrbBreakoutStrategy,
  goldFuturesToriTradesTrendlineBreakRetestStrategy,
  goldFuturesToriTradesTrendlineBreakRetestOnAudNzdOppositeStrategy,
  goldFuturesToriTradesTrendlineBreakRetestOnEurCadStrategy,
  goldFuturesToriTradesTrendlineBreakRetestOnUsdCadOppositeStrategy,
  goldFuturesToriTradesTrendlineBreakRetestOnUsdJpyStrategy,
  goldSpotEchoNeuralMeanReversionStrategy,
  goldSpotEchoNeuralMeanReversionBalancedStrategy,
  goldSpotEchoNeuralMomentumStrategy,
  goldSpotEchoNeuralMomentumBalancedStrategy,
  goldSpotToriTradesTrendlineBreakRetestStrategy,
  nasdaq100FuturesClaytraderSupportResistanceRetestStrategy,
  nasdaq100FuturesDecileForwardEdge5mStrategy,
  nasdaq100FuturesMomentumStrategy,
  nasdaq100FuturesPercentileRangeStudy15mStrategy,
  nasdaq100FuturesPercentileRangeStudy1hStrategy,
  nasdaq100FuturesPercentileRangeStudy1mStrategy,
  nasdaq100FuturesPercentileRangeStudy30mStrategy,
  nasdaq100FuturesPercentileRangeStudy5mStrategy,
  nasdaq100FuturesRedditEmaPullbackStrategy,
  nasdaq100FuturesRedditOrbBreakoutStrategy,
  nasdaq100FuturesRedditOrbRetestStrategy,
  nasdaq100FuturesRoundHundredRejection15mStrategy,
  nasdaq100FuturesSma20SupportBounce1hStrategy,
  nasdaq100FuturesSma50Sma200Cross15mStrategy,
  nasdaq100FuturesToriTradesTrendlineBreakRetestStrategy,
  nzdUsdNySweepBayesStrategy,
  nzdUsdNySweepLogitStrategy,
  nzdUsdNySweepStumpStrategy,
  russell2000FuturesClaytraderSupportResistanceRetestStrategy,
  russell2000FuturesIctSweepFvgStrategy,
  russell2000FuturesRedditOrbRetestStrategy,
  silverFuturesRedditCapitulationReversionStrategy,
  sp500FuturesRedditOrbBreakoutStrategy,
  sp500FuturesToriTradesTrendlineBreakRetestStrategy,
  usTreasury10yNoteFuturesMomentumOppositeStrategy,
  usdCadNySweepBayesStrategy,
  usdCadNySweepLogitStrategy,
  usdCadNySweepLogitPriorDayTargetStrategy,
  usdCadNySweepLogitPriorDayTargetOnCanadianDollarFuturesOppositeStrategy,
  usdCadNySweepStumpStrategy,
  usdChfNySweepStumpStrategy,
  usdJpyNySweepBayesStrategy,
  usdJpyNySweepBayesOnCopperFuturesStrategy,
  usdJpyNySweepBayesOnDowJonesFuturesStrategy,
  usdJpyNySweepLogitStrategy,
  usdJpyNySweepLogitOnSp500FuturesStrategy,
  usdJpyNySweepStumpStrategy,
  usdJpyNySweepStumpOnCopperFuturesStrategy,
  usdJpyNySweepStumpPriorDayTargetStrategy,
  usdJpyNySweepStumpPriorDayTargetOnNaturalGasFuturesOppositeStrategy,
];

export function strategyForPhase(phase: string): StrategyDefinition | undefined {
  return STRATEGY_DEFINITIONS.find((strategy) => strategy.phase === phase);
}
