import strategy000 from "@strategy/competition_usd_jpy_us_first30_last30_reversal_signalweekdayside_direction_opposite_entryminute_930_ex_40e6d9ae/strategy";
import strategy001 from "@strategy/competition_eur_chf_daily_tsmom_next_rth_signalmonth_direction_momentum_entryminute_570_exitminute_945_391afa4a/strategy";
import strategy002 from "@strategy/competition_eur_jpy_us_first30_last30_momentum_signalweekdayside_direction_same_entryminute_930_exitba_0a4a3f58/strategy";
import strategy003 from "@strategy/competition_usd_cad_daily_tsmom_next_overnight_signalmonth_direction_momentum_entryminute_945_exitminu_dca02dc1/strategy";
import strategy004 from "@strategy/competition_usd_cad_us_first30_last30_momentum_signalmonth_direction_same_entryminute_930_exitbarminut_c1317995/strategy";
import strategy005 from "@strategy/competition_usd_jpy_asia_range_london_breakout_signalweekdayside_breakendminute_360_breakstartminute_1_83470b07/strategy";
import strategy006 from "@strategy/competition_eur_jpy_daily_tsmom_next_rth_signalmonth_direction_momentum_entryminute_570_exitminute_945_563aa3f1/strategy";
import strategy007 from "@strategy/competition_gbp_jpy_london_first30_ny_open_reversal_signalmonth_direction_opposite_entryminute_480_exi_d549e3a7/strategy";
import strategy008 from "@strategy/competition_nzd_usd_daily_tsmom_next_rth_signalmonth_direction_contrarian_entryminute_570_exitminute_9_183b1d88/strategy";
import strategy009 from "@strategy/aud_usd_ny_sweep_bayes/strategy";
import strategy010 from "@strategy/competition_gbp_jpy_daily_tsmom_next_overnight_signalmonth_direction_contrarian_entryminute_945_exitmi_ab520ea7/strategy";
import strategy011 from "@strategy/competition_gbp_jpy_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exitbarminute_945_ming_297a7a1d/strategy";
import strategy012 from "@strategy/competition_aud_usd_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_c8c5223e/strategy";
import strategy013 from "@strategy/competition_gbp_usd_us_first30_last30_reversal_signalmonth_direction_opposite_entryminute_930_exitbarm_9b2547fb/strategy";
import strategy014 from "@strategy/competition_aud_usd_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exitbarminute_660_ming_5c432e4e/strategy";
import strategy015 from "@strategy/competition_japanese_yen_futures_us_first30_last30_reversal_signalweekdayside_direction_opposite_entry_11a69e11/strategy";
import strategy016 from "@strategy/competition_micro_bitcoin_futures_daily_tsmom_next_overnight_signalweekdayside_direction_contrarian_en_6003fc2d/strategy";
import strategy017 from "@strategy/competition_crude_oil_futures_overnight_close_to_open_bias_signalmonth_entry_prior_rth_close_exit_ny_o_315d7644/strategy";
import strategy018 from "@strategy/competition_russell_2000_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exitbarmi_801e97d2/strategy";
import strategy019 from "@strategy/competition_australian_dollar_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exit_dcd12f25/strategy";
import strategy020 from "@strategy/competition_canadian_dollar_futures_overnight_close_to_open_bias_signalmonth_entry_prior_rth_close_exi_31e5e01a/strategy";
import strategy021 from "@strategy/competition_us_treasury_5y_note_futures_us_first30_last30_momentum_signalweekdayside_direction_same_en_1942c62b/strategy";
import strategy022 from "@strategy/competition_dow_jones_futures_daily_tsmom_next_overnight_signalweekdayside_direction_momentum_entrymin_c2a8817b/strategy";
import strategy023 from "@strategy/competition_new_zealand_dollar_futures_us_first30_last30_reversal_signalmonth_direction_opposite_entry_ce284576/strategy";
import strategy024 from "@strategy/competition_us_treasury_2y_note_futures_us_first30_last30_momentum_signalweekdayside_direction_same_en_339e7451/strategy";
import strategy025 from "@strategy/competition_gold_futures_daily_tsmom_next_overnight_signalweekdayside_direction_momentum_entryminute_9_c8e1caae/strategy";
import strategy026 from "@strategy/competition_new_zealand_dollar_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exi_7ad85d81/strategy";
import strategy027 from "@strategy/competition_euro_futures_daily_tsmom_next_rth_signalmonth_direction_contrarian_entryminute_570_exitmin_0b54da46/strategy";
import strategy028 from "@strategy/competition_us_treasury_5y_note_futures_us_first30_last30_momentum_signalweekdayside_direction_same_en_62e3b6d2/strategy";
import strategy029 from "@strategy/competition_canadian_dollar_futures_daily_tsmom_next_overnight_signalmonth_direction_momentum_entrymin_eee85315/strategy";
import strategy030 from "@strategy/competition_australian_dollar_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_exit_1aa4fa28/strategy";
import strategy031 from "@strategy/competition_silver_futures_london_first30_ny_open_momentum_signalweekdayside_direction_same_entryminut_5ce60b39/strategy";
import strategy032 from "@strategy/competition_australian_dollar_futures_us_first30_last30_reversal_signalmonth_direction_opposite_entrym_77aa2b55/strategy";
import strategy033 from "@strategy/competition_us_treasury_2y_note_futures_ny_open_gap_fade_signalmonth_direction_fade_entryminute_570_ex_d2289e05/strategy";
import strategy034 from "@strategy/eur_usd_ny_sweep_logit_on_british_pound_futures/strategy";
import strategy035 from "@strategy/nasdaq_100_futures_round_hundred_rejection_15m/strategy";

import type { StrategyDefinition } from "@/lib/strategy-definition";

export type { StrategyDefinition, StrategySignal } from "@/lib/strategy-definition";

export const STRATEGY_DEFINITIONS: StrategyDefinition[] = [
  strategy000,
  strategy001,
  strategy002,
  strategy003,
  strategy004,
  strategy005,
  strategy006,
  strategy007,
  strategy008,
  strategy009,
  strategy010,
  strategy011,
  strategy012,
  strategy013,
  strategy014,
  strategy015,
  strategy016,
  strategy017,
  strategy018,
  strategy019,
  strategy020,
  strategy021,
  strategy022,
  strategy023,
  strategy024,
  strategy025,
  strategy026,
  strategy027,
  strategy028,
  strategy029,
  strategy030,
  strategy031,
  strategy032,
  strategy033,
  strategy034,
  strategy035
];
