import audUsdNySweepBayesPriorDayTargetStrategy from "@strategy/aud_usd_ny_sweep_bayes_prior_day_target/strategy";
import audUsdNySweepLogitStrategy from "@strategy/aud_usd_ny_sweep_logit/strategy";
import audUsdNySweepLogitOnBritishPoundFuturesStrategy from "@strategy/aud_usd_ny_sweep_logit_on_british_pound_futures/strategy";
import audUsdNySweepLogitOnEuroFuturesStrategy from "@strategy/aud_usd_ny_sweep_logit_on_euro_futures/strategy";
import audUsdNySweepStumpStrategy from "@strategy/aud_usd_ny_sweep_stump/strategy";
import copperFuturesRedditCapitulationReversionStrategy from "@strategy/copper_futures_reddit_capitulation_reversion/strategy";
import copperFuturesRedditOrbBreakoutOppositeStrategy from "@strategy/copper_futures_reddit_orb_breakout_opposite/strategy";
import crudeOilFuturesIctSweepFvgStrategy from "@strategy/crude_oil_futures_ict_sweep_fvg/strategy";
import crudeOilFuturesMomentumStrategy from "@strategy/crude_oil_futures_momentum/strategy";
import crudeOilFuturesRedditOrbBreakoutStrategy from "@strategy/crude_oil_futures_reddit_orb_breakout/strategy";
import crudeOilFuturesToriTradesTrendlineBreakRetestStrategy from "@strategy/crude_oil_futures_tori_trades_trendline_break_retest/strategy";
import dowJonesFuturesRedditCapitulationReversionStrategy from "@strategy/dow_jones_futures_reddit_capitulation_reversion/strategy";
import dowJonesFuturesRedditCapitulationReversionOnUsdChfStrategy from "@strategy/dow_jones_futures_reddit_capitulation_reversion_on_usd_chf/strategy";
import dowJonesFuturesRedditEmaPullbackStrategy from "@strategy/dow_jones_futures_reddit_ema_pullback/strategy";
import dowJonesFuturesRedditOrbBreakoutOppositeStrategy from "@strategy/dow_jones_futures_reddit_orb_breakout_opposite/strategy";
import dowJonesFuturesRedditOrbRetestStrategy from "@strategy/dow_jones_futures_reddit_orb_retest/strategy";
import eurUsdNySweepBayesStrategy from "@strategy/eur_usd_ny_sweep_bayes/strategy";
import eurUsdNySweepLogitStrategy from "@strategy/eur_usd_ny_sweep_logit/strategy";
import eurUsdNySweepLogitOnBritishPoundFuturesStrategy from "@strategy/eur_usd_ny_sweep_logit_on_british_pound_futures/strategy";
import eurUsdNySweepLogitOnEuroFuturesStrategy from "@strategy/eur_usd_ny_sweep_logit_on_euro_futures/strategy";
import eurUsdNySweepStumpStrategy from "@strategy/eur_usd_ny_sweep_stump/strategy";
import eurUsdNySweepStumpPriorDayTargetStrategy from "@strategy/eur_usd_ny_sweep_stump_prior_day_target/strategy";
import gbpUsdIctTurtleSoupStrategy from "@strategy/gbp_usd_ict_turtle_soup/strategy";
import gbpUsdMeanReversionStrategy from "@strategy/gbp_usd_mean_reversion/strategy";
import gbpUsdNySweepBayesStrategy from "@strategy/gbp_usd_ny_sweep_bayes/strategy";
import gbpUsdNySweepBayesPriorDayTargetOnSp500FuturesStrategy from "@strategy/gbp_usd_ny_sweep_bayes_prior_day_target_on_sp_500_futures/strategy";
import gbpUsdNySweepLogitStrategy from "@strategy/gbp_usd_ny_sweep_logit/strategy";
import gbpUsdNySweepStumpOnBritishPoundFuturesStrategy from "@strategy/gbp_usd_ny_sweep_stump_on_british_pound_futures/strategy";
import gbpUsdNySweepStumpOnEuroFuturesStrategy from "@strategy/gbp_usd_ny_sweep_stump_on_euro_futures/strategy";
import goldFuturesIctSweepFvgStrategy from "@strategy/gold_futures_ict_sweep_fvg/strategy";
import goldFuturesRedditEmaPullbackStrategy from "@strategy/gold_futures_reddit_ema_pullback/strategy";
import goldFuturesRedditOrbBreakoutStrategy from "@strategy/gold_futures_reddit_orb_breakout/strategy";
import nasdaq100FuturesMomentumStrategy from "@strategy/nasdaq_100_futures_momentum/strategy";
import nasdaq100FuturesRedditEmaPullbackStrategy from "@strategy/nasdaq_100_futures_reddit_ema_pullback/strategy";
import nasdaq100FuturesRedditOrbBreakoutStrategy from "@strategy/nasdaq_100_futures_reddit_orb_breakout/strategy";
import nasdaq100FuturesRedditOrbRetestStrategy from "@strategy/nasdaq_100_futures_reddit_orb_retest/strategy";
import nasdaq100FuturesToriTradesTrendlineBreakRetestStrategy from "@strategy/nasdaq_100_futures_tori_trades_trendline_break_retest/strategy";
import nzdUsdNySweepBayesStrategy from "@strategy/nzd_usd_ny_sweep_bayes/strategy";
import nzdUsdNySweepLogitStrategy from "@strategy/nzd_usd_ny_sweep_logit/strategy";
import nzdUsdNySweepStumpStrategy from "@strategy/nzd_usd_ny_sweep_stump/strategy";
import russell2000FuturesIctSweepFvgStrategy from "@strategy/russell_2000_futures_ict_sweep_fvg/strategy";
import russell2000FuturesRedditOrbRetestStrategy from "@strategy/russell_2000_futures_reddit_orb_retest/strategy";
import silverFuturesRedditCapitulationReversionStrategy from "@strategy/silver_futures_reddit_capitulation_reversion/strategy";
import sp500FuturesRedditOrbBreakoutStrategy from "@strategy/sp_500_futures_reddit_orb_breakout/strategy";
import sp500FuturesToriTradesTrendlineBreakRetestStrategy from "@strategy/sp_500_futures_tori_trades_trendline_break_retest/strategy";
import usTreasury10yNoteFuturesMomentumOppositeStrategy from "@strategy/us_treasury_10y_note_futures_momentum_opposite/strategy";
import usdCadNySweepBayesStrategy from "@strategy/usd_cad_ny_sweep_bayes/strategy";
import usdCadNySweepLogitStrategy from "@strategy/usd_cad_ny_sweep_logit/strategy";
import usdCadNySweepLogitPriorDayTargetStrategy from "@strategy/usd_cad_ny_sweep_logit_prior_day_target/strategy";
import usdCadNySweepLogitPriorDayTargetOnCanadianDollarFuturesOppositeStrategy from "@strategy/usd_cad_ny_sweep_logit_prior_day_target_on_canadian_dollar_futures_opposite/strategy";
import usdCadNySweepStumpStrategy from "@strategy/usd_cad_ny_sweep_stump/strategy";
import usdChfNySweepStumpStrategy from "@strategy/usd_chf_ny_sweep_stump/strategy";
import usdJpyNySweepBayesStrategy from "@strategy/usd_jpy_ny_sweep_bayes/strategy";
import usdJpyNySweepBayesOnDowJonesFuturesStrategy from "@strategy/usd_jpy_ny_sweep_bayes_on_dow_jones_futures/strategy";
import usdJpyNySweepLogitStrategy from "@strategy/usd_jpy_ny_sweep_logit/strategy";
import usdJpyNySweepLogitOnSp500FuturesStrategy from "@strategy/usd_jpy_ny_sweep_logit_on_sp_500_futures/strategy";
import usdJpyNySweepStumpOnCopperFuturesStrategy from "@strategy/usd_jpy_ny_sweep_stump_on_copper_futures/strategy";
import usdJpyNySweepStumpPriorDayTargetOnNaturalGasFuturesOppositeStrategy from "@strategy/usd_jpy_ny_sweep_stump_prior_day_target_on_natural_gas_futures_opposite/strategy";

import type { StrategyDefinition } from "@/lib/strategy-definition";

export type { StrategyDefinition, StrategySignal } from "@/lib/strategy-definition";

export const STRATEGY_DEFINITIONS: StrategyDefinition[] = [
  audUsdNySweepBayesPriorDayTargetStrategy,
  audUsdNySweepLogitStrategy,
  audUsdNySweepLogitOnBritishPoundFuturesStrategy,
  audUsdNySweepLogitOnEuroFuturesStrategy,
  audUsdNySweepStumpStrategy,
  copperFuturesRedditCapitulationReversionStrategy,
  copperFuturesRedditOrbBreakoutOppositeStrategy,
  crudeOilFuturesIctSweepFvgStrategy,
  crudeOilFuturesMomentumStrategy,
  crudeOilFuturesRedditOrbBreakoutStrategy,
  crudeOilFuturesToriTradesTrendlineBreakRetestStrategy,
  dowJonesFuturesRedditCapitulationReversionStrategy,
  dowJonesFuturesRedditCapitulationReversionOnUsdChfStrategy,
  dowJonesFuturesRedditEmaPullbackStrategy,
  dowJonesFuturesRedditOrbBreakoutOppositeStrategy,
  dowJonesFuturesRedditOrbRetestStrategy,
  eurUsdNySweepBayesStrategy,
  eurUsdNySweepLogitStrategy,
  eurUsdNySweepLogitOnBritishPoundFuturesStrategy,
  eurUsdNySweepLogitOnEuroFuturesStrategy,
  eurUsdNySweepStumpStrategy,
  eurUsdNySweepStumpPriorDayTargetStrategy,
  gbpUsdIctTurtleSoupStrategy,
  gbpUsdMeanReversionStrategy,
  gbpUsdNySweepBayesStrategy,
  gbpUsdNySweepBayesPriorDayTargetOnSp500FuturesStrategy,
  gbpUsdNySweepLogitStrategy,
  gbpUsdNySweepStumpOnBritishPoundFuturesStrategy,
  gbpUsdNySweepStumpOnEuroFuturesStrategy,
  goldFuturesIctSweepFvgStrategy,
  goldFuturesRedditEmaPullbackStrategy,
  goldFuturesRedditOrbBreakoutStrategy,
  nasdaq100FuturesMomentumStrategy,
  nasdaq100FuturesRedditEmaPullbackStrategy,
  nasdaq100FuturesRedditOrbBreakoutStrategy,
  nasdaq100FuturesRedditOrbRetestStrategy,
  nasdaq100FuturesToriTradesTrendlineBreakRetestStrategy,
  nzdUsdNySweepBayesStrategy,
  nzdUsdNySweepLogitStrategy,
  nzdUsdNySweepStumpStrategy,
  russell2000FuturesIctSweepFvgStrategy,
  russell2000FuturesRedditOrbRetestStrategy,
  silverFuturesRedditCapitulationReversionStrategy,
  sp500FuturesRedditOrbBreakoutStrategy,
  sp500FuturesToriTradesTrendlineBreakRetestStrategy,
  usTreasury10yNoteFuturesMomentumOppositeStrategy,
  usdCadNySweepBayesStrategy,
  usdCadNySweepLogitStrategy,
  usdCadNySweepLogitPriorDayTargetStrategy,
  usdCadNySweepLogitPriorDayTargetOnCanadianDollarFuturesOppositeStrategy,
  usdCadNySweepStumpStrategy,
  usdChfNySweepStumpStrategy,
  usdJpyNySweepBayesStrategy,
  usdJpyNySweepBayesOnDowJonesFuturesStrategy,
  usdJpyNySweepLogitStrategy,
  usdJpyNySweepLogitOnSp500FuturesStrategy,
  usdJpyNySweepStumpOnCopperFuturesStrategy,
  usdJpyNySweepStumpPriorDayTargetOnNaturalGasFuturesOppositeStrategy,
];

export function strategyForPhase(phase: string): StrategyDefinition | undefined {
  return STRATEGY_DEFINITIONS.find((strategy) => strategy.phase === phase);
}
