
const FEED='https://raw.githubusercontent.com/hajixd/signal-console/main/alerts.json';
const STARTING_EQUITY=10000, STOCK_NOTIONAL=1000, CRYPTO_NOTIONAL=1000;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>(n<0?'-':'')+'$'+Math.abs(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const pct=n=>(n>=0?'+':'')+n.toFixed(2)+'%';
let events=[],trades=[],page='home',signalCategory='all',homeFilter='open',tradeFilter='open',alertFilter='all',accountFilter='all',chartRange='1D',currentTrade=null,chartPts=[];
function numeric(v){if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(/[$,]/g,''));return Number.isFinite(n)&&n>=0?n:null}
function normalizeEvent(a){return {...a,id:String(a.id||`${a.tradeId}-${a.eventType}-${a.timestamp}`),eventType:String(a.eventType||a.type||'entry').toLowerCase(),tradeId:String(a.tradeId||a.id||''),timestamp:a.timestamp,asset:a.asset||a.ticker||a.symbol||'Unknown',entryPrice:numeric(a.entryPrice??a.details?.entryPrice),exitPrice:numeric(a.exitPrice??a.details?.exitPrice),currentPrice:numeric(a.currentPrice??a.details?.currentPrice),score:numeric(a.score)||0,reasons:Array.isArray(a.reasons)?a.reasons:[a.summary].filter(Boolean)}}
function buildTrades(evts){const map=new Map(),seen=new Set();[...evts].sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp)).forEach(e=>{if(seen.has(e.id)||!e.tradeId)return;seen.add(e.id);let t=map.get(e.tradeId);if(e.eventType==='entry'&&!t&&e.entryPrice>0){t={...e,entryAt:e.timestamp,currentPrice:e.currentPrice??e.entryPrice,markAt:e.markAt||e.timestamp,status:'open',events:[e],optionContracts:numeric(e.optionContracts)||1};map.set(e.tradeId,t)}else if(t&&t.status==='open'){if(e.eventType==='exit'&&e.exitPrice!==null){Object.assign(t,{status:'closed',exitAt:e.timestamp,exitPrice:e.exitPrice,currentPrice:e.exitPrice,markAt:e.timestamp,exitReasons:e.reasons,exitSummary:e.summary});t.events.push(e)}else if(['mark','update'].includes(e.eventType)&&e.currentPrice!==null){t.currentPrice=e.currentPrice;t.markAt=e.timestamp;t.events.push(e)}}});return [...map.values()].sort((a,b)=>Date.parse(b.entryAt)-Date.parse(a.entryAt))}
function exposure(t){if(t.system==='options')return (t.entryPrice||0)*100*(t.optionContracts||1);return t.system==='meme'?CRYPTO_NOTIONAL:STOCK_NOTIONAL}
function tradePnl(t){if(!(t.entryPrice>0))return 0;const px=t.status==='closed'?t.exitPrice:(t.currentPrice??t.entryPrice);if(px===null||!Number.isFinite(px))return 0;const side=t.system==='options'?1:(/^(short|bearish)$/i.test(t.direction)?-1:1);return t.system==='options'?(px-t.entryPrice)*100*(t.optionContracts||1):side*exposure(t)*(px/t.entryPrice-1)}
function tradePct(t){const exp=exposure(t);return exp?tradePnl(t)/exp*100:0}
function timeAgo(t){const s=Math.max(0,(Date.now()-new Date(t))/1000);if(s<60)return'just now';if(s<3600)return Math.floor(s/60)+'m';if(s<86400)return Math.floor(s/3600)+'h';return Math.floor(s/86400)+'d'}
function systemLabel(s){return s==='meme'?'Tokens':s==='penny'?'Penny':s==='options'?'Options':'Signal'}
function iconText(t){return t.system==='options'?'OP':t.system==='penny'?'ST':'M'}
function setPage(p){if(p==='portfolio')p='home';if(!['home','trades','alerts','performance','search','account','research'].includes(p))p='home';page=p;$$('[data-page]').forEach(b=>{if(b.dataset.page===p)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});$$('.nav-btn[data-page],.mobile-tab[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));['home','trades','alerts','performance','search','account','research'].forEach(v=>$('#'+v+'View').classList.toggle('hide',v!==p));$('#mobileTitle').textContent=({home:'Investing',trades:'Positions',alerts:'Alerts',account:'Portfolio',research:'Discover'})[p]||p[0].toUpperCase()+p.slice(1);render();chartPinned=false;chartLeave();syncControlStates();if(location.hash.slice(1)!==p)history.pushState(null,'','#'+p);scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
function calcStats(){const closed=trades.filter(t=>t.status==='closed'),open=trades.filter(t=>t.status==='open');const realized=closed.reduce((s,t)=>s+tradePnl(t),0),unreal=open.reduce((s,t)=>s+tradePnl(t),0),total=realized+unreal;const wins=closed.filter(t=>tradePnl(t)>0),losses=closed.filter(t=>tradePnl(t)<0);const grossWin=wins.reduce((s,t)=>s+tradePnl(t),0),grossLoss=Math.abs(losses.reduce((s,t)=>s+tradePnl(t),0));return{closed,open,realized,unreal,total,equity:STARTING_EQUITY+total,winRate:closed.length?wins.length/closed.length*100:0,profitFactor:grossLoss?grossWin/grossLoss:grossWin?Infinity:0,avgWinner:wins.length?grossWin/wins.length:0,avgLoser:losses.length?losses.reduce((s,t)=>s+tradePnl(t),0)/losses.length:0}}
function equityCurve(filter=accountFilter){const selected=filter==='all'?trades:trades.filter(t=>t.system===filter);const pts=[],marks=new Map();const start=Math.min(Date.now(),...selected.map(t=>Date.parse(t.entryAt)));pts.push({time:start-1,value:STARTING_EQUITY,label:'Start'});const history=selected.flatMap(t=>t.events.map(e=>({t,e}))).sort((a,b)=>Date.parse(a.e.timestamp)-Date.parse(b.e.timestamp));for(const {t,e} of history){const px=e.eventType==='exit'?e.exitPrice:e.eventType==='entry'?e.entryPrice:e.currentPrice;if(px===null)continue;marks.set(t.tradeId,tradePnl({...t,status:'open',currentPrice:px}));pts.push({time:Date.parse(e.timestamp),value:STARTING_EQUITY+[...marks.values()].reduce((a,b)=>a+b,0),label:t.asset+' '+e.eventType})}pts.push({time:Date.now(),value:STARTING_EQUITY+selected.reduce((sum,t)=>sum+tradePnl(t),0),label:'Latest recorded value'});return pts}
function maxDrawdown(curve){let peak=curve[0]?.value||STARTING_EQUITY,dd=0;curve.forEach(p=>{peak=Math.max(peak,p.value);dd=Math.min(dd,(p.value-peak)/peak*100)});return dd}
function renderChart(){const all=equityCurve(),now=Date.now(),durations={'1D':864e5,'1W':7*864e5,'1M':30*864e5,'3M':90*864e5,'1Y':365*864e5};const start=chartRange==='ALL'?Math.min(all[0].time,now-864e5):chartRange==='YTD'?new Date(new Date().getFullYear(),0,1).getTime():now-durations[chartRange];const previous=all.filter(p=>p.time<=start).at(-1);const pts=[{time:start,value:previous?.value??STARTING_EQUITY,label:'Period start'},...all.filter(p=>p.time>start)];const vals=pts.map(p=>p.value),min=Math.min(...vals),max=Math.max(...vals),span=max-min;chartPts=pts.map(p=>({...p,x:(p.time-start)/Math.max(1,now-start)*820,y:span?20+(max-p.value)/span*290:165}));$('#chartScrubber').max=Math.max(0,chartPts.length-1);$('#chartScrubber').value=chartIndex<0?chartPts.length-1:Math.min(chartIndex,chartPts.length-1);const d=chartPts.map((p,i)=>`${i?'L':'M'} ${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(' ');$('#chartLine').setAttribute('d',d);$('#chartFill').setAttribute('d',d+' L 820 330 L 0 330 Z');const color=pts.at(-1).value<pts[0].value?'var(--red)':'var(--green)';$('#chartLine').style.stroke=color;$('#dot').style.fill=color;$('#portfolioChange').innerHTML=`<span style="color:${color}">${pts.at(-1).value<pts[0].value?'▼':'▲'} ${money(pts.at(-1).value-pts[0].value)} (${pct((pts.at(-1).value/pts[0].value-1)*100)})</span><span class="hero-note">${chartRange==='1D'?'Past day':chartRange==='ALL'?'All time':chartRange}</span>`}
function rowHtml(t){const pnl=tradePnl(t),pc=tradePct(t),state=t.status==='closed'?'Closed':(pnl>=0?'Mid-trade':'Mid-trade');return `<div class="trade-row" data-trade="${esc(t.tradeId)}"><div class="asset"><div class="asset-icon">${iconText(t)}</div><div class="asset-copy"><div class="asset-title">${esc(t.title)}${t.demo?'<span class="demo-tag">Demo</span>':''}</div><div class="asset-sub">${systemLabel(t.system)} · ${t.status==='closed'?`closed ${timeAgo(t.exitAt)} ago`:`open ${timeAgo(t.entryAt)} ago`}</div></div></div><div class="cell"><strong>${money(exposure(t))}</strong><span>Exposure</span></div><div class="cell ${pnl>=0?'positive':'negative'}"><strong>${money(pnl)}</strong><span>${pct(pc)}</span></div><div class="status-pill ${t.status==='closed'?'closed':''}">${state}</div></div>`}
function alertHtml(e){const isExit=e.eventType==='exit',isResearch=e.eventType==='research';return `<div class="trade-row" data-event="${esc(e.id||'')}"><div class="asset"><div class="asset-icon">${isExit?'OUT':iconText(e)}</div><div class="asset-copy"><div class="asset-title">${esc(e.title||e.asset)}${e.demo?'<span class="demo-tag">Demo</span>':''}</div><div class="asset-sub">${isResearch?'Research':isExit?'Exit alert':'Entry alert'} · ${systemLabel(e.system)} · ${timeAgo(e.timestamp)} ago</div></div></div><div class="cell"><strong>${e.score||'—'}</strong><span>Score</span></div><div class="cell"><strong>${esc(e.horizon||'—')}</strong><span>Horizon</span></div><div class="status-pill ${isExit?'exit':''}">${isResearch?'Research':isExit?'Exit':'Entry'}</div></div>`}
function bindRows(){$$('[data-trade],[data-event]').forEach(r=>{r.tabIndex=0;r.setAttribute('role','button');r.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();r.click()}}});$$('[data-trade]').forEach(r=>r.onclick=()=>openTrade(trades.find(t=>t.tradeId===r.dataset.trade)));$$('[data-event]').forEach(r=>r.onclick=()=>{const e=events.find(x=>(x.id||'')===r.dataset.event);openAlert(e)})}
function render(){const s=calcStats();$('#portfolioValue').textContent=money(s.equity);const tc=s.total>=0?'positive':'negative',uc=s.unreal>=0?'positive':'negative';$('#portfolioChange').innerHTML=`<span class="${tc}"><span class="rh-triangle">${s.total>=0?'▲':'▼'}</span>${money(s.total)} (${pct(s.total/STARTING_EQUITY*100)})</span><span class="hero-note">Total return</span>`;$('#openPnlChange').innerHTML=`<span class="${uc}"><span class="rh-triangle">${s.unreal>=0?'▲':'▼'}</span>${money(s.unreal)} (${pct(s.unreal/STARTING_EQUITY*100)})</span><span class="hero-note">Open positions</span>`;const committed=s.open.reduce((sum,t)=>sum+exposure(t),0);$('#buyingPower').innerHTML=`${money(Math.max(0,STARTING_EQUITY+s.realized-committed))}`;$('#totalReturn').textContent=pct(s.total/STARTING_EQUITY*100);$('#totalReturn').className=s.total>=0?'positive':'negative';$('#winRate').textContent=s.closed.length?s.winRate.toFixed(1)+'%':'—';$('#openCount').textContent=s.open.length;$('#closedCount').textContent=s.closed.length;
 let homeItems=(homeFilter==='open'?s.open:homeFilter==='closed'?s.closed:trades);if(accountFilter==='closed')homeItems=s.closed;else if(accountFilter!=='all')homeItems=homeItems.filter(t=>t.system===accountFilter);$('#positionList').innerHTML=homeItems.length?homeItems.slice(0,8).map(rowHtml).join(''):'<div class="empty"><strong>No positions here</strong>New qualifying alerts will appear automatically.</div>';
 const tradeItems=tradeFilter==='open'?s.open:tradeFilter==='closed'?s.closed:trades;$('#tradesList').innerHTML=tradeItems.length?tradeItems.map(rowHtml).join(''):'<div class="empty"><strong>No trades</strong></div>';$('#tradeCountLabel').textContent=`${tradeItems.length} ${tradeItems.length===1?'trade':'trades'}`;
 const ae=events.filter(e=>['entry','exit','research'].includes(e.eventType)).sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp)).filter(e=>alertFilter==='all'||e.eventType===alertFilter);$('#alertsList').innerHTML=ae.length?ae.map(alertHtml).join(''):'<div class="empty"><strong>No qualifying alerts yet</strong>Completed scans can produce no signals. Check scanner coverage below; new entries and exits appear here automatically.</div>';
 $('#perfProfit').textContent=money(s.total);$('#perfProfit').className='hero-value '+(s.total>=0?'positive':'negative');$('#profitFactor').textContent=s.profitFactor===Infinity?'∞':s.profitFactor.toFixed(2);$('#avgWinner').textContent=money(s.avgWinner);$('#avgLoser').textContent=money(s.avgLoser);$('#maxDrawdown').textContent=pct(maxDrawdown(equityCurve('all')));$('#performanceList').innerHTML=s.closed.length?s.closed.map(rowHtml).join(''):'<div class="empty"><strong>No closed trades</strong></div>';
 $('#railOpenCount').textContent=s.open.length;$('#railPositions').innerHTML=s.open.slice(0,6).map(t=>`<div class="position-row" data-trade="${esc(t.tradeId)}"><div class="position-main"><div class="mini-icon">${iconText(t)}</div><div><div class="position-name">${esc(t.asset)}</div><div class="position-sub">${esc(t.contract||systemLabel(t.system))}</div></div></div><div class="pnl ${tradePnl(t)>=0?'positive':'negative'}">${pct(tradePct(t))}<small>${money(tradePnl(t))}</small></div></div>`).join('')||'<div class="position-row"><div class="muted">No open positions</div></div>';
 $('#railAlerts').innerHTML=ae.slice(0,5).map(e=>`<div class="alert-row" data-event="${esc(e.id||'')}"><div class="position-main"><div class="mini-icon">${e.eventType==='exit'?'OUT':iconText(e)}</div><div><div class="position-name">${esc(e.asset)}</div><div class="position-sub">${e.eventType==='research'?'Research':e.eventType==='exit'?'Exit':'Entry'} · ${timeAgo(e.timestamp)} ago</div></div></div><div class="pnl ${e.eventType==='exit'?'negative':'positive'}">${e.eventType==='research'?'RESEARCH':e.eventType==='exit'?'EXIT':'ENTER'}</div></div>`).join('')||'<div class="position-row muted">No qualifying alerts yet</div>';renderChart();renderSearch();renderStatus();renderAccount();renderDashboard();renderSelectedPortfolio();syncControlStates();if(chartPinned&&chartIndex>=0)inspectPoint(chartIndex);bindRows()}
function openTrade(t){if(!t)return;$('#marketBtn').textContent='Open market page';currentTrade=t;$('#marketBtn').hidden=!/^https?:\/\//i.test(t.href||'');$('#copyBtn').hidden=!(t.contract||t.asset);const pnl=tradePnl(t),pc=tradePct(t);$('#sheetLabel').textContent=t.status==='closed'?'Closed trade':'Open position';$('#sheetTitle').textContent=t.title;$('#sheetSub').textContent=`${systemLabel(t.system)} · ${t.status==='closed'?'Closed':'Mid-trade'}`;$('#sheetValue').textContent=money(pnl);$('#sheetValue').className='sheet-value '+(pnl>=0?'positive':'negative');$('#sheetChange').textContent=`${pct(pc)} total return`;$('#sheetChange').className='sheet-change '+(pnl>=0?'positive':'negative');const detailValue=v=>typeof v==='object'?JSON.stringify(v):v;const details={'Entry':t.entryPrice||'—','Latest recorded':t.status==='closed'?(t.exitPrice??'—'):(t.currentPrice??'—'),'Quote time':new Date(t.markAt).toLocaleString(),'Exposure':money(exposure(t)),'Status':t.status==='closed'?'Closed':'Mid-trade','Entered':new Date(t.entryAt).toLocaleString(),'Exited':t.exitAt?new Date(t.exitAt).toLocaleString():'—','Score':t.score?t.score+'/100':'—','Horizon':t.horizon||'—',...t.details};$('#sheetDetails').innerHTML=Object.entries(details).slice(0,14).map(([k,v])=>`<div><small>${esc(k)}</small><strong>${esc(detailValue(v))}</strong></div>`).join('');const rs=t.status==='closed'&&t.exitReasons?.length?t.exitReasons:t.reasons;$('#sheetReasons').innerHTML=(rs?.length?rs:[t.summary||'Signal research thesis.']).map(x=>`<li>${esc(x)}</li>`).join('');$('#sheet').inert=false;previousFocus=document.activeElement;$('#sheet').classList.add('open');$('#backdrop').classList.add('open');document.body.classList.add('modal-open');$$('.desktop-header,.mobile-header').forEach(e=>e.inert=true);$('.shell').inert=true;$('.mobile-nav').inert=true;$('#sheet').scrollTop=0;$('#sheetClose').focus()}
let previousFocus=null;
function closeSheet(){if(!$('#sheet').classList.contains('open'))return;$$('.desktop-header,.mobile-header').forEach(e=>e.inert=false);$('#sheet').inert=true;$('.shell').inert=false;$('.mobile-nav').inert=false;previousFocus?.focus();$('#sheet').classList.remove('open');$('#backdrop').classList.remove('open');document.body.classList.remove('modal-open');$('#sheet').style.transform=''}
function toast(x){$('#toast').textContent=x;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),1300)}
let chartPinned=false,chartPointer=null,chartIndex=-1,lastHaptic=0;
function haptic(){if(!hapticsEnabled||typeof navigator.vibrate!=='function'||Date.now()-lastHaptic<65)return;lastHaptic=Date.now();try{navigator.vibrate(8)}catch{}}
function inspectPoint(index){if(!chartPts.length)return;const i=Math.max(0,Math.min(chartPts.length-1,index)),p=chartPts[i];if(i!==chartIndex&&chartPointer!==null)haptic();chartIndex=i;$('#cross').setAttribute('x1',p.x);$('#cross').setAttribute('x2',p.x);$('#cross').style.opacity=1;$('#dot').setAttribute('cx',p.x);$('#dot').setAttribute('cy',p.y);$('#dot').style.opacity=1;const when=new Date(p.time).toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});$('#chartTip').textContent=when+' · '+money(p.value);$('#chartTip').style.opacity=1;$('#portfolioValue').textContent=money(p.value);$('#chartScrubber').value=i;$('#chartScrubber').setAttribute('aria-valuetext',when+', '+money(p.value)+', '+p.label);$('#chartReset').hidden=false;}
function chartMove(e){if(chartPinned&&chartPointer===null)return;if(e.pointerType==='touch'&&chartPointer===null)return;const r=$('#chart').getBoundingClientRect();if(!r.width||!chartPts.length)return;const x=Math.max(0,Math.min(820,(e.clientX-r.left)/r.width*820));let best=0;chartPts.forEach((p,i)=>{if(Math.abs(p.x-x)<Math.abs(chartPts[best].x-x))best=i});inspectPoint(best)}
function chartLeave(){if(chartPinned||chartPointer!==null)return;chartIndex=-1;$('#cross').style.opacity=0;$('#dot').style.opacity=0;$('#chartTip').style.opacity=0;$('#chartReset').hidden=true;renderSelectedPortfolio()}
let feedMeta={},feedError='',lastSync=null,loading=false,searchCategory='';
async function load(){if(loading)return;loading=true;renderStatus();try{const r=await fetch(FEED+'?t='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();if(!Array.isArray(data.alerts))throw new Error('Invalid alert feed');events=data.alerts.filter(a=>a&&typeof a==='object'&&!a.demo&&!/demo|sample/i.test(String(a.id||''))&&!/\[demo\]/i.test(String(a.title||''))).map(normalizeEvent).filter(a=>Number.isFinite(Date.parse(a.timestamp)));feedMeta=data;trades=buildTrades(events);lastSync=new Date();feedError='';}catch(e){feedError='Feed unavailable. '+(lastSync?'Showing the last successful update.':'No trade data loaded.');}finally{loading=false;render()}}
function renderSearch(){const q=$('#mobileSearch').value.trim().toLowerCase();const match=t=>(!searchCategory||t.system===searchCategory)&&[t.asset,t.title,t.contract,t.summary].join(' ').toLowerCase().includes(q);const found=trades.filter(match),research=events.filter(e=>e.eventType==='research'&&match(e));$('#searchResults').innerHTML=found.length||research.length?found.map(rowHtml).join('')+research.map(alertHtml).join(''):`<div class="empty"><strong>${q?'No matching results':'No signals in this category yet'}</strong>${q?'Try a symbol, contract or research keyword.':'Latest scan checks in Discover explain current coverage.'}</div>`;bindRows()}

function renderAccount(){const s=calcStats();$('#accountValue').textContent=money(s.equity);$('#accountReturn').textContent=pct(s.total/STARTING_EQUITY*100)+' total paper return';$('#accountRealized').textContent=money(s.realized);$('#accountOpen').textContent=s.open.length;$('#accountFeed').textContent=feedError||(lastSync?'Feed checked '+lastSync.toLocaleTimeString():'Connecting to alert feed…')}
function scannerEvidence(v){const missing=Array.isArray(v?.missingData)?v.missingData:[],sources=Array.isArray(v?.sources)?v.sources:[];return (missing.length?`<p class="pending">Missing checks: ${esc(missing.join(', '))}</p>`:'')+(sources.length?'<ul class="source-list">'+sources.map(x=>`<li>${/^https?:\/\//i.test(x.url||'')?`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.name||x.url)}</a>`:esc(x.name||'Source')} · ${esc(x.status||'Unverified')}</li>`).join('')+'</ul>':'')}
function scannerHealth(v){
 const age=v?.checkedAt?Date.now()-Date.parse(v.checkedAt):Infinity;
 const started=v?.startedAt?Date.now()-Date.parse(v.startedAt):Infinity;
 if(v?.status==='running')return {label:started>=0&&started<45*60000?'Scanning':'Incomplete run',tone:'pending'};
 if(!v||!Number.isFinite(age))return {label:'Not verified',tone:'pending'};
 if(age<0||age>90*60000)return {label:'Check-in overdue',tone:'pending'};
 return {label:({ok:'Checked',market_closed:'Market closed',data_limited:'Limited coverage',error:'Scan failed'})[v.status]||'Unknown status',tone:v.status==='ok'?'positive':v.status==='market_closed'?'muted':'pending'};
}
function renderStatus(){
 $('#feedStatus').textContent=loading?'Refreshing…':feedError?'Feed unavailable':lastSync?'Feed connected':'Connecting';
 $('.live').classList.toggle('unavailable',!!feedError);
 $('#feedError').textContent=feedError;$('#feedError').classList.toggle('hide',!feedError);
 ['refresh','mobileRefresh','accountRefresh','scannerRefresh'].forEach(id=>{const b=$('#'+id);if(b){b.disabled=loading;b.setAttribute('aria-busy',String(loading))}});
 const next=new Date();next.setHours(next.getHours()+1,0,0,0);
 $('#nextScan').textContent='Next scheduled scan: '+new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit',timeZone:'America/Los_Angeles',timeZoneName:'short'}).format(next)+'. Results appear after each scan finishes. Start and completion times may vary.';
 const keys=['meme','options','penny'];const expanded=new Set($$('#scannerStatus details[open]').map(d=>d.dataset.system));
 $('#scannerStatus').innerHTML=keys.map(key=>{const v=feedMeta.scanners?.[key],h=scannerHealth(v);return `<details class="scanner-detail" data-system="${key}" ${expanded.has(key)?'open':''}><summary class="scanner-row"><div><strong>${systemLabel(key)} scanner</strong><small>${v?.checkedAt&&Number.isFinite(Date.parse(v.checkedAt))?'Last completed '+esc(new Date(v.checkedAt).toLocaleString()):'No completed check-in received'}</small>${v?.startedAt&&v?.scheduledFor&&Date.parse(v.startedAt)-Date.parse(v.scheduledFor)>300000?`<small class="pending">Started ${Math.round((Date.parse(v.startedAt)-Date.parse(v.scheduledFor))/60000)} min after target</small>`:''}</div><span class="scanner-state ${h.tone}">${h.label}<span aria-hidden="true"> ›</span></span></summary><p>${esc(v?.summary||'Awaiting a verified scan report. An enabled schedule does not guarantee source coverage.')}</p>${scannerEvidence(v)}${key==='meme'?'<p>Checks wallet activity and verified launch / public-figure news. Unverified endorsements do not qualify.</p>':''}</details>`}).join('');
 $('#scanHistory').innerHTML=(Array.isArray(feedMeta.scanHistory)?feedMeta.scanHistory:[]).slice().sort((a,b)=>Date.parse(b.checkedAt)-Date.parse(a.checkedAt)).slice(0,21).map(v=>`<div class=history-row><strong>${esc(systemLabel(v.system))}</strong><span>${esc(new Date(v.checkedAt).toLocaleString())}</span><p>${esc(v.summary)}</p></div>`).join('')||'<p class=feed-note>History will appear as the updated scanners complete runs. Latest completed checks are shown above.</p>';
 const overdue=keys.filter(k=>['pending'].includes(scannerHealth(feedMeta.scanners?.[k]).tone)).length;
 $('#homeFeedStatus').textContent=feedError?'Feed unavailable · View status':overdue?`${overdue} scanner${overdue>1?'s need':' needs'} attention · View status`:'Hourly scanners · View latest checks';
 $('#homeFeedStatus').classList.toggle('pending',!!overdue||!!feedError);
}
function openAlert(e){if(!e)return;const t=trades.find(t=>t.tradeId===e.tradeId);if(t){openTrade(t);return}
 openTrade({...e,status:'research',entryAt:e.timestamp,markAt:e.timestamp,entryPrice:0,currentPrice:0,details:e.details||{}});
 $('#sheetLabel').textContent='Research alert';$('#sheetSub').textContent=systemLabel(e.system)+' · '+new Date(e.timestamp).toLocaleString();$('#sheetValue').textContent='No paper position';$('#sheetChange').textContent='Research only · entry checks remain incomplete.';$('#marketBtn').textContent='Open source';
 $('#sheetDetails').innerHTML=`<div><small>Asset</small><strong>${esc(e.asset)}</strong></div><div><small>Summary</small><strong>${esc(e.summary||'No summary provided')}</strong></div><div><small>Pending verification</small><strong>${esc((e.missingData||e.details?.missingData||[]).join?.(', ')||'See research rationale')}</strong></div>`;
}
$$('[data-page]').forEach(b=>b.onclick=()=>setPage(b.dataset.page));$$('[data-filter]').forEach(b=>b.onclick=()=>{homeFilter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});$$('[data-trades-filter]').forEach(b=>b.onclick=()=>{tradeFilter=b.dataset.tradesFilter;$$('[data-trades-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});$$('[data-alert-filter]').forEach(b=>b.onclick=()=>{alertFilter=b.dataset.alertFilter;$$('[data-alert-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#refresh').onclick=$('#mobileRefresh').onclick=()=>{load();toast('Refreshing')};$('#sheetClose').onclick=$('#backdrop').onclick=closeSheet;$('#copyBtn').onclick=async()=>{try{await navigator.clipboard.writeText(currentTrade?.contract||currentTrade?.asset||'');toast('Copied')}catch{toast('Copy unavailable in this browser')}};$('#marketBtn').onclick=()=>{if(/^https?:\/\//i.test(currentTrade?.href||''))window.open(currentTrade.href,'_blank','noopener');else toast('No market link available')};$('#chartWrap').addEventListener('pointermove',chartMove);$('#chartWrap').addEventListener('pointerleave',chartLeave);$('#search').addEventListener('input',e=>{setPage('search');$('#mobileSearch').value=e.target.value;renderSearch()});$('#accountTab').onclick=()=>setPage('account');$$('[data-account]').forEach(b=>b.onclick=()=>{chartPinned=false;chartPointer=null;chartLeave();accountFilter=b.dataset.account;$$('[data-account]').forEach(x=>x.classList.toggle('active',x===b));render()});$$('[data-range]').forEach(b=>b.onclick=()=>{chartPinned=false;chartPointer=null;chartLeave();chartRange=b.dataset.range;$$('[data-range]').forEach(x=>x.classList.toggle('active',x===b));renderChart();syncControlStates()});
let dragStart=null,dragY=0;$('#sheetHandle').addEventListener('touchstart',e=>{dragStart=e.touches[0].clientY;dragY=0},{passive:true});$('#sheetHandle').addEventListener('touchmove',e=>{if(dragStart===null)return;dragY=Math.max(0,e.touches[0].clientY-dragStart);$('#sheet').style.transform=`translateY(${dragY}px)`},{passive:true});$('#sheetHandle').addEventListener('touchend',()=>{if(dragY>90)closeSheet();else $('#sheet').style.transform='';dragStart=null;dragY=0});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSheet();if(e.key==='Tab'&&$('#sheet').classList.contains('open')){const btns=[...$('#sheet').querySelectorAll('button:not([hidden]):not(:disabled)')],first=btns[0],last=btns.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
$('#mobileSearch').addEventListener('input',()=>{$('#search').value=$('#mobileSearch').value;renderSearch()});$('#accountRefresh').onclick=$('#scannerRefresh').onclick=load;$$('[data-explore]').forEach(b=>b.onclick=()=>{searchCategory=b.dataset.explore;$$('[data-explore]').forEach(x=>x.classList.toggle('active',x===b));renderSearch()});

function renderDashboard(){
 const selected=e=>signalCategory==='all'||e.system===signalCategory;
 const activity=events.filter(e=>selected(e)&&['entry','exit','research'].includes(e.eventType)).sort((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp));
 const recent=activity.filter(e=>Date.now()-Date.parse(e.timestamp)<864e5);
 $('#deskDate').textContent=new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric'}).format(new Date());
 $('#signalCount').textContent=lastSync?recent.filter(e=>e.eventType!=='research').length:'—';
 $('#researchCount').textContent=lastSync?recent.filter(e=>e.eventType==='research').length:'—';
 $('#deskOpenCount').textContent=lastSync?trades.filter(t=>selected(t)&&t.status==='open').length:'—';
 $('#activityMeta').textContent=feedError?'Last available data':lastSync?'Synced '+lastSync.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'Connecting…';
 $('#signalFeed').innerHTML=activity.length?activity.slice(0,30).map(alertHtml).join(''):`<div class="desk-empty"><span class="empty-symbol" aria-hidden="true">↗</span><strong>${feedError?'Waiting for the feed':!lastSync?'Connecting to your research desk':'No qualifying signals yet'}</strong><p>${feedError?'Use Refresh to reconnect. Your last loaded data stays available.':!lastSync?'Loading scanner reports and verified events.':'Read the latest briefings below. Research appears separately from verified paper entries; an empty feed does not mean a scanner passed every data check.'}</p></div>`;
 $('#briefings').innerHTML=['meme','options','penny'].filter(system=>selected({system})).map(key=>{const v=feedMeta.scanners?.[key],h=scannerHealth(v);return `<article class="briefing"><div class="briefing-head"><span class="briefing-icon">${key==='meme'?'T':key==='options'?'O':'P'}</span><h3>${systemLabel(key)}</h3><span class="health-badge ${h.tone}">${h.label}</span></div><p>${esc(v?.summary||'No completed scan report received yet.')}</p><div class="briefing-foot"><span>${v?.checkedAt?'Completed '+esc(timeAgo(v.checkedAt))+' ago':'Awaiting check-in'}</span><span>Hourly</span></div></article>`}).join('');
}
$$('[data-signal-category]').forEach(b=>b.onclick=()=>{signalCategory=b.dataset.signalCategory;$$('[data-signal-category]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});renderDashboard();bindRows()});

function renderSelectedPortfolio(){const selected=accountFilter==='all'?trades:trades.filter(t=>t.system===accountFilter);const total=selected.reduce((n,t)=>n+tradePnl(t),0),open=selected.filter(t=>t.status==='open'),realized=selected.filter(t=>t.status==='closed').reduce((n,t)=>n+tradePnl(t),0);$('#portfolioValue').textContent=money(STARTING_EQUITY+total);const closed=selected.filter(t=>t.status==='closed');$('#totalReturn').textContent=pct(total/STARTING_EQUITY*100);$('#totalReturn').className=total>=0?'positive':'negative';$('#openCount').textContent=open.length;$('#closedCount').textContent=closed.length;$('#winRate').textContent=closed.length?(closed.filter(t=>tradePnl(t)>0).length/closed.length*100).toFixed(1)+'%':'—';$('#chartHint').textContent=selected.length?'Hover, drag or use keyboard to inspect recorded values':'No paper trades yet · chart shows starting capital';$('#openPnlChange').innerHTML=`<span class="${total>=0?'positive':'negative'}">${money(open.reduce((n,t)=>n+tradePnl(t),0))}</span><span class="hero-note">Open paper return</span>`;$('#buyingPower').textContent=money(Math.max(0,STARTING_EQUITY+realized-open.reduce((n,t)=>n+exposure(t),0)));}
$$('[data-discover]').forEach(b=>b.onclick=()=>{signalCategory=b.dataset.discover;$$('[data-signal-category]').forEach(x=>{x.classList.toggle('active',x.dataset.signalCategory===signalCategory);x.setAttribute('aria-pressed',String(x.dataset.signalCategory===signalCategory))});setPage('research')});
document.addEventListener('visibilitychange' ,()=>{if(!document.hidden)load()});

let hapticsEnabled=false;try{hapticsEnabled=localStorage.getItem('signal-haptics')==='on'}catch{}
const supportsHaptics=typeof navigator.vibrate==='function';
function renderHaptics(){const b=$('#hapticToggle');b.disabled=!supportsHaptics;b.setAttribute('aria-checked',String(hapticsEnabled&&supportsHaptics));b.textContent=supportsHaptics?(hapticsEnabled?'On':'Off'):'Unavailable';$('#hapticHelp').textContent=supportsHaptics?'Light feedback for selections; device settings may mute it.':'This browser does not provide web vibration. Visual feedback stays on.'}
$('#hapticToggle').onclick=()=>{hapticsEnabled=!hapticsEnabled;try{localStorage.setItem('signal-haptics',hapticsEnabled?'on':'off')}catch{}renderHaptics();haptic()};renderHaptics();
function syncControlStates(){$$('[data-account],[data-range],[data-filter],[data-trades-filter],[data-alert-filter],[data-explore]').forEach(b=>b.setAttribute('aria-pressed',String(b.classList.contains('active'))))}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-trade],[data-event],summary');if(b&&!b.disabled){haptic();syncControlStates()}});
$('#chartWrap').addEventListener('pointerdown',e=>{if(!e.isPrimary||e.button>0)return;chartPinned=false;chartPointer=e.pointerId;$('#chartWrap').setPointerCapture(e.pointerId);chartMove(e)});
$('#chartWrap').addEventListener('pointerup',()=>{chartPointer=null;chartPinned=true});
$('#chartWrap').addEventListener('pointercancel',()=>{chartPointer=null;chartPinned=false;chartLeave()});
$('#chartScrubber').addEventListener('input',e=>{chartPinned=true;inspectPoint(Number(e.target.value));haptic()});
$('#chartReset').onclick=()=>{chartPinned=false;chartPointer=null;chartLeave()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){chartPinned=false;chartPointer=null;chartLeave()}});
window.addEventListener('popstate',()=>{if($('#sheet').classList.contains('open'))closeSheet();setPage(location.hash.slice(1)||'home')});

if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'}).catch(()=>{}));setPage(location.hash.slice(1)||'home');load();setInterval(load,60000);
