
const FEED='https://raw.githubusercontent.com/hajixd/signal-console/main/alerts.json';
const STARTING_EQUITY=10000, STOCK_NOTIONAL=1000, CRYPTO_NOTIONAL=1000;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>(n<0?'-':'')+'$'+Math.abs(n).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const pct=n=>(n>=0?'+':'')+n.toFixed(2)+'%';
let events=[],trades=[],page='home',homeFilter='open',tradeFilter='open',alertFilter='all',accountFilter='all',chartRange='1D',currentTrade=null,chartPts=[];
function numeric(v){if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(/[$,]/g,''));return Number.isFinite(n)&&n>=0?n:null}
function normalizeEvent(a){return {...a,id:String(a.id||`${a.tradeId}-${a.eventType}-${a.timestamp}`),eventType:String(a.eventType||a.type||'entry').toLowerCase(),tradeId:String(a.tradeId||a.id||''),timestamp:a.timestamp,asset:a.asset||a.ticker||a.symbol||'Unknown',entryPrice:numeric(a.entryPrice??a.details?.entryPrice),exitPrice:numeric(a.exitPrice??a.details?.exitPrice),currentPrice:numeric(a.currentPrice??a.details?.currentPrice),score:numeric(a.score)||0,reasons:Array.isArray(a.reasons)?a.reasons:[a.summary].filter(Boolean)}}
function buildTrades(evts){const map=new Map(),seen=new Set();[...evts].sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp)).forEach(e=>{if(seen.has(e.id)||!e.tradeId)return;seen.add(e.id);let t=map.get(e.tradeId);if(e.eventType==='entry'&&!t&&e.entryPrice>0){t={...e,entryAt:e.timestamp,currentPrice:e.currentPrice??e.entryPrice,markAt:e.markAt||e.timestamp,status:'open',events:[e],optionContracts:numeric(e.optionContracts)||1};map.set(e.tradeId,t)}else if(t&&t.status==='open'){if(e.eventType==='exit'&&e.exitPrice!==null){Object.assign(t,{status:'closed',exitAt:e.timestamp,exitPrice:e.exitPrice,currentPrice:e.exitPrice,markAt:e.timestamp,exitReasons:e.reasons,exitSummary:e.summary});t.events.push(e)}else if(['mark','update'].includes(e.eventType)&&e.currentPrice!==null){t.currentPrice=e.currentPrice;t.markAt=e.timestamp;t.events.push(e)}}});return [...map.values()].sort((a,b)=>Date.parse(b.entryAt)-Date.parse(a.entryAt))}
function exposure(t){if(t.system==='options')return (t.entryPrice||0)*100*(t.optionContracts||1);return t.system==='meme'?CRYPTO_NOTIONAL:STOCK_NOTIONAL}
function tradePnl(t){if(!(t.entryPrice>0))return 0;const px=t.status==='closed'?t.exitPrice:(t.currentPrice??t.entryPrice);if(px===null||!Number.isFinite(px))return 0;const side=t.system==='options'?1:(/^(short|bearish)$/i.test(t.direction)?-1:1);return t.system==='options'?(px-t.entryPrice)*100*(t.optionContracts||1):side*exposure(t)*(px/t.entryPrice-1)}
function tradePct(t){const exp=exposure(t);return exp?tradePnl(t)/exp*100:0}
function timeAgo(t){const s=Math.max(0,(Date.now()-new Date(t))/1000);if(s<60)return'just now';if(s<3600)return Math.floor(s/60)+'m';if(s<86400)return Math.floor(s/3600)+'h';return Math.floor(s/86400)+'d'}
function systemLabel(s){return s==='meme'?'Meme coin':s==='penny'?'Penny stock':s==='options'?'Option':'Signal'}
function iconText(t){return t.system==='options'?'OP':t.system==='penny'?'ST':'M'}
function setPage(p){page=p;$$('.nav-btn[data-page],.mobile-tab[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));['home','trades','alerts','performance','search','account'].forEach(v=>$('#'+v+'View').classList.toggle('hide',v!==p));$('#mobileTitle').textContent=p==='home'?'Signal':p[0].toUpperCase()+p.slice(1);render();if(innerWidth<701)scrollTo({top:0,behavior:'smooth'})}
function calcStats(){const closed=trades.filter(t=>t.status==='closed'),open=trades.filter(t=>t.status==='open');const realized=closed.reduce((s,t)=>s+tradePnl(t),0),unreal=open.reduce((s,t)=>s+tradePnl(t),0),total=realized+unreal;const wins=closed.filter(t=>tradePnl(t)>0),losses=closed.filter(t=>tradePnl(t)<0);const grossWin=wins.reduce((s,t)=>s+tradePnl(t),0),grossLoss=Math.abs(losses.reduce((s,t)=>s+tradePnl(t),0));return{closed,open,realized,unreal,total,equity:STARTING_EQUITY+total,winRate:closed.length?wins.length/closed.length*100:0,profitFactor:grossLoss?grossWin/grossLoss:grossWin?Infinity:0,avgWinner:wins.length?grossWin/wins.length:0,avgLoser:losses.length?losses.reduce((s,t)=>s+tradePnl(t),0)/losses.length:0}}
function equityCurve(){const pts=[],marks=new Map();const start=Math.min(Date.now(),...trades.map(t=>Date.parse(t.entryAt)));pts.push({time:start-1,value:STARTING_EQUITY,label:'Start'});const history=trades.flatMap(t=>t.events.map(e=>({t,e}))).sort((a,b)=>Date.parse(a.e.timestamp)-Date.parse(b.e.timestamp));for(const {t,e} of history){const px=e.eventType==='exit'?e.exitPrice:e.eventType==='entry'?e.entryPrice:e.currentPrice;if(px===null)continue;marks.set(t.tradeId,tradePnl({...t,status:'open',currentPrice:px}));pts.push({time:Date.parse(e.timestamp),value:STARTING_EQUITY+[...marks.values()].reduce((a,b)=>a+b,0),label:t.asset+' '+e.eventType})}pts.push({time:Date.now(),value:calcStats().equity,label:'Latest recorded value'});return pts}
function maxDrawdown(curve){let peak=curve[0]?.value||STARTING_EQUITY,dd=0;curve.forEach(p=>{peak=Math.max(peak,p.value);dd=Math.min(dd,(p.value-peak)/peak*100)});return dd}
function renderChart(){const all=equityCurve(),now=Date.now(),durations={'1D':864e5,'1W':7*864e5,'1M':30*864e5,'3M':90*864e5,'1Y':365*864e5};const start=chartRange==='ALL'?Math.min(all[0].time,now-864e5):chartRange==='YTD'?new Date(new Date().getFullYear(),0,1).getTime():now-durations[chartRange];const previous=all.filter(p=>p.time<=start).at(-1);const pts=[{time:start,value:previous?.value??STARTING_EQUITY,label:'Period start'},...all.filter(p=>p.time>start)];const vals=pts.map(p=>p.value),min=Math.min(...vals),max=Math.max(...vals),span=max-min;chartPts=pts.map(p=>({...p,x:(p.time-start)/Math.max(1,now-start)*820,y:span?20+(max-p.value)/span*290:165}));const d=chartPts.map((p,i)=>`${i?'L':'M'} ${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(' ');$('#chartLine').setAttribute('d',d);$('#chartFill').setAttribute('d',d+' L 820 330 L 0 330 Z');const color=pts.at(-1).value<pts[0].value?'var(--red)':'var(--green)';$('#chartLine').style.stroke=color;$('#dot').style.fill=color;$('#portfolioChange').innerHTML=`<span style="color:${color}">${pts.at(-1).value<pts[0].value?'▼':'▲'} ${money(pts.at(-1).value-pts[0].value)} (${pct((pts.at(-1).value/pts[0].value-1)*100)})</span><span class="hero-note">${chartRange==='1D'?'Past day':chartRange==='ALL'?'All time':chartRange}</span>`}
function rowHtml(t){const pnl=tradePnl(t),pc=tradePct(t),state=t.status==='closed'?'Closed':(pnl>=0?'Mid-trade':'Mid-trade');return `<div class="trade-row" data-trade="${esc(t.tradeId)}"><div class="asset"><div class="asset-icon">${iconText(t)}</div><div class="asset-copy"><div class="asset-title">${esc(t.title)}${t.demo?'<span class="demo-tag">Demo</span>':''}</div><div class="asset-sub">${systemLabel(t.system)} · ${t.status==='closed'?`closed ${timeAgo(t.exitAt)} ago`:`open ${timeAgo(t.entryAt)} ago`}</div></div></div><div class="cell"><strong>${money(exposure(t))}</strong><span>Exposure</span></div><div class="cell ${pnl>=0?'positive':'negative'}"><strong>${money(pnl)}</strong><span>${pct(pc)}</span></div><div class="status-pill ${t.status==='closed'?'closed':''}">${state}</div></div>`}
function alertHtml(e){const isExit=e.eventType==='exit';return `<div class="trade-row" data-event="${esc(e.id||'')}"><div class="asset"><div class="asset-icon">${isExit?'OUT':iconText(e)}</div><div class="asset-copy"><div class="asset-title">${esc(e.title||e.asset)}${e.demo?'<span class="demo-tag">Demo</span>':''}</div><div class="asset-sub">${isExit?'Exit alert':'Entry alert'} · ${systemLabel(e.system)} · ${timeAgo(e.timestamp)} ago</div></div></div><div class="cell"><strong>${e.score||'—'}</strong><span>Score</span></div><div class="cell"><strong>${esc(e.horizon||'—')}</strong><span>Horizon</span></div><div class="status-pill ${isExit?'exit':''}">${isExit?'Exit':'Entry'}</div></div>`}
function bindRows(){$$('[data-trade],[data-event]').forEach(r=>{r.tabIndex=0;r.setAttribute('role','button');r.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();r.click()}}});$$('[data-trade]').forEach(r=>r.onclick=()=>openTrade(trades.find(t=>t.tradeId===r.dataset.trade)));$$('[data-event]').forEach(r=>r.onclick=()=>{const e=events.find(x=>(x.id||'')===r.dataset.event);openTrade(trades.find(t=>t.tradeId===e?.tradeId))})}
function render(){const s=calcStats();$('#portfolioValue').textContent=money(s.equity);const tc=s.total>=0?'positive':'negative',uc=s.unreal>=0?'positive':'negative';$('#portfolioChange').innerHTML=`<span class="${tc}"><span class="rh-triangle">${s.total>=0?'▲':'▼'}</span>${money(s.total)} (${pct(s.total/STARTING_EQUITY*100)})</span><span class="hero-note">Total return</span>`;$('#openPnlChange').innerHTML=`<span class="${uc}"><span class="rh-triangle">${s.unreal>=0?'▲':'▼'}</span>${money(s.unreal)} (${pct(s.unreal/STARTING_EQUITY*100)})</span><span class="hero-note">Open positions</span>`;const committed=s.open.reduce((sum,t)=>sum+exposure(t),0);$('#buyingPower').innerHTML=`${money(Math.max(0,STARTING_EQUITY+s.realized-committed))} <b>›</b>`;$('#totalReturn').textContent=pct(s.total/STARTING_EQUITY*100);$('#totalReturn').className=s.total>=0?'positive':'negative';$('#winRate').textContent=s.closed.length?s.winRate.toFixed(1)+'%':'—';$('#openCount').textContent=s.open.length;$('#closedCount').textContent=s.closed.length;
 let homeItems=(homeFilter==='open'?s.open:homeFilter==='closed'?s.closed:trades);if(accountFilter==='closed')homeItems=s.closed;else if(accountFilter!=='all')homeItems=homeItems.filter(t=>t.system===accountFilter);$('#positionList').innerHTML=homeItems.length?homeItems.slice(0,8).map(rowHtml).join(''):'<div class="empty"><strong>No positions here</strong>New qualifying alerts will appear automatically.</div>';
 const tradeItems=tradeFilter==='open'?s.open:tradeFilter==='closed'?s.closed:trades;$('#tradesList').innerHTML=tradeItems.length?tradeItems.map(rowHtml).join(''):'<div class="empty"><strong>No trades</strong></div>';$('#tradeCountLabel').textContent=`${tradeItems.length} ${tradeItems.length===1?'trade':'trades'}`;
 const ae=events.filter(e=>['entry','exit'].includes(e.eventType)).sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp)).filter(e=>alertFilter==='all'||e.eventType===alertFilter);$('#alertsList').innerHTML=ae.length?ae.map(alertHtml).join(''):'<div class="empty"><strong>No alerts</strong></div>';
 $('#perfProfit').textContent=money(s.total);$('#perfProfit').className='hero-value '+(s.total>=0?'positive':'negative');$('#profitFactor').textContent=s.profitFactor===Infinity?'∞':s.profitFactor.toFixed(2);$('#avgWinner').textContent=money(s.avgWinner);$('#avgLoser').textContent=money(s.avgLoser);$('#maxDrawdown').textContent=pct(maxDrawdown(equityCurve()));$('#performanceList').innerHTML=s.closed.length?s.closed.map(rowHtml).join(''):'<div class="empty"><strong>No closed trades</strong></div>';
 $('#railOpenCount').textContent=s.open.length;$('#railPositions').innerHTML=s.open.slice(0,6).map(t=>`<div class="position-row" data-trade="${esc(t.tradeId)}"><div class="position-main"><div class="mini-icon">${iconText(t)}</div><div><div class="position-name">${esc(t.asset)}</div><div class="position-sub">${esc(t.contract||systemLabel(t.system))}</div></div></div><div class="pnl ${tradePnl(t)>=0?'positive':'negative'}">${pct(tradePct(t))}<small>${money(tradePnl(t))}</small></div></div>`).join('')||'<div class="position-row"><div class="muted">No open positions</div></div>';
 $('#railAlerts').innerHTML=ae.slice(0,5).map(e=>`<div class="alert-row" data-event="${esc(e.id||'')}"><div class="position-main"><div class="mini-icon">${e.eventType==='exit'?'OUT':iconText(e)}</div><div><div class="position-name">${esc(e.asset)}</div><div class="position-sub">${e.eventType==='exit'?'Exit':'Entry'} · ${timeAgo(e.timestamp)} ago</div></div></div><div class="pnl ${e.eventType==='exit'?'negative':'positive'}">${e.eventType==='exit'?'EXIT':'ENTER'}</div></div>`).join('');renderChart();renderSearch();renderStatus();renderAccount();bindRows()}
function openTrade(t){if(!t)return;currentTrade=t;const pnl=tradePnl(t),pc=tradePct(t);$('#sheetLabel').textContent=t.status==='closed'?'Closed trade':'Open position';$('#sheetTitle').textContent=t.title;$('#sheetSub').textContent=`${systemLabel(t.system)} · ${t.status==='closed'?'Closed':'Mid-trade'}`;$('#sheetValue').textContent=money(pnl);$('#sheetValue').className='sheet-value '+(pnl>=0?'positive':'negative');$('#sheetChange').textContent=`${pct(pc)} total return`;$('#sheetChange').className='sheet-change '+(pnl>=0?'positive':'negative');const details={'Entry':t.entryPrice||'—','Latest recorded':t.status==='closed'?(t.exitPrice??'—'):(t.currentPrice??'—'),'Quote time':new Date(t.markAt).toLocaleString(),'Exposure':money(exposure(t)),'Status':t.status==='closed'?'Closed':'Mid-trade','Entered':new Date(t.entryAt).toLocaleString(),'Exited':t.exitAt?new Date(t.exitAt).toLocaleString():'—','Score':t.score?t.score+'/100':'—','Horizon':t.horizon||'—',...t.details};$('#sheetDetails').innerHTML=Object.entries(details).slice(0,14).map(([k,v])=>`<div><small>${esc(k)}</small><strong>${esc(v)}</strong></div>`).join('');const rs=t.status==='closed'&&t.exitReasons?.length?t.exitReasons:t.reasons;$('#sheetReasons').innerHTML=(rs?.length?rs:[t.summary||'Signal research thesis.']).map(x=>`<li>${esc(x)}</li>`).join('');$('#sheet').inert=false;previousFocus=document.activeElement;$('#sheet').classList.add('open');$('#backdrop').classList.add('open');document.body.classList.add('modal-open');$('.shell').inert=true;$('.mobile-nav').inert=true;$('#sheet').scrollTop=0;$('#sheetClose').focus()}
let previousFocus=null;
function closeSheet(){$('#sheet').inert=true;$('.shell').inert=false;$('.mobile-nav').inert=false;previousFocus?.focus();$('#sheet').classList.remove('open');$('#backdrop').classList.remove('open');document.body.classList.remove('modal-open');$('#sheet').style.transform=''}
function toast(x){$('#toast').textContent=x;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),1300)}
function chartMove(e){if(!chartPts.length)return;const r=$('#chart').getBoundingClientRect(),x=(e.clientX-r.left)/r.width*820,p=chartPts.reduce((a,b)=>Math.abs(b.x-x)<Math.abs(a.x-x)?b:a,chartPts[0]);$('#cross').setAttribute('x1',p.x);$('#cross').setAttribute('x2',p.x);$('#cross').style.opacity=1;$('#dot').setAttribute('cx',p.x);$('#dot').setAttribute('cy',p.y);$('#dot').style.opacity=1;$('#chartTip').innerHTML=`${new Date(p.time).toLocaleDateString()} · <strong>${money(p.value)}</strong>`;$('#chartTip').style.opacity=1}
function chartLeave(){$('#cross').style.opacity=0;$('#dot').style.opacity=0;$('#chartTip').style.opacity=0}
let feedMeta={},feedError='',lastSync=null,loading=false,searchCategory='';
async function load(){if(loading)return;loading=true;try{const r=await fetch(FEED+'?t='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();if(!Array.isArray(data.alerts))throw new Error('Invalid alert feed');events=data.alerts.filter(a=>a&&typeof a==='object'&&!a.demo&&!/demo|sample/i.test(String(a.id||''))&&!/\[demo\]/i.test(String(a.title||''))).map(normalizeEvent).filter(a=>Number.isFinite(Date.parse(a.timestamp)));feedMeta=data;trades=buildTrades(events);lastSync=new Date();feedError='';}catch(e){feedError='Feed unavailable. '+(lastSync?'Showing the last successful update.':'No trade data loaded.');}finally{loading=false;render()}}
function renderSearch(){const q=$('#mobileSearch').value.trim().toLowerCase();const found=trades.filter(t=>(!searchCategory||t.system===searchCategory)&&[t.asset,t.title,t.contract].join(' ').toLowerCase().includes(q));$('#searchResults').innerHTML=found.length?found.map(rowHtml).join(''):`<div class="empty"><strong>${q?'No matching trades':'No signals yet'}</strong>${q?'Try another symbol or contract.':'Verified entries will appear here when a scanner finds a qualifying setup.'}</div>`;bindRows()}
function renderAccount(){const s=calcStats();$('#accountValue').textContent=money(s.equity);$('#accountReturn').textContent=pct(s.total/STARTING_EQUITY*100)+' total paper return';$('#accountRealized').textContent=money(s.realized);$('#accountOpen').textContent=s.open.length;$('#accountFeed').textContent=feedError||(lastSync?'Feed checked '+lastSync.toLocaleTimeString():'Connecting to alert feed…')}
function renderStatus(){$('#feedStatus').textContent=feedError?'Feed unavailable':lastSync?'Feed connected':'Connecting';$('.live').classList.toggle('unavailable',!!feedError);$('#feedError').textContent=feedError;$('#feedError').classList.toggle('hide',!feedError);$('#scannerStatus').innerHTML=['options','penny','meme'].map(key=>{const v=feedMeta.scanners?.[key],age=v?.checkedAt?Date.now()-Date.parse(v.checkedAt):Infinity;const fresh=age>=0&&age<90*60000;const label=!v?'Awaiting first status':!fresh?'Status overdue':v.status==='ok'?'Last check completed':v.status==='market_closed'?'Market closed':'Data limited';return `<div class="scanner-row"><div><strong>${systemLabel(key)} scanner</strong><small>${v?.checkedAt?esc(new Date(v.checkedAt).toLocaleString()):'Hourly schedule · status not yet verified'}</small></div><span class="scanner-state ${fresh&&v?.status==='ok'?'positive':''}">${label}</span></div>`}).join('')}
$$('[data-page]').forEach(b=>b.onclick=()=>setPage(b.dataset.page));$$('[data-filter]').forEach(b=>b.onclick=()=>{homeFilter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});$$('[data-trades-filter]').forEach(b=>b.onclick=()=>{tradeFilter=b.dataset.tradesFilter;$$('[data-trades-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});$$('[data-alert-filter]').forEach(b=>b.onclick=()=>{alertFilter=b.dataset.alertFilter;$$('[data-alert-filter]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#refresh').onclick=$('#mobileRefresh').onclick=()=>{load();toast('Refreshing')};$('#sheetClose').onclick=$('#backdrop').onclick=closeSheet;$('#copyBtn').onclick=()=>{navigator.clipboard?.writeText(currentTrade?.contract||currentTrade?.asset||'').then(()=>toast('Copied')).catch(()=>toast('Could not copy'))};$('#marketBtn').onclick=()=>{if(/^https?:\/\//i.test(currentTrade?.href||''))window.open(currentTrade.href,'_blank','noopener');else toast('No market link available')};$('#chartWrap').addEventListener('pointermove',chartMove);$('#chartWrap').addEventListener('pointerleave',chartLeave);$('#chartWrap').addEventListener('pointerup',chartLeave);$('#search').addEventListener('input',e=>{setPage('search');$('#mobileSearch').value=e.target.value;renderSearch()});$('#accountTab').onclick=()=>setPage('account');$$('[data-account]').forEach(b=>b.onclick=()=>{accountFilter=b.dataset.account;$$('[data-account]').forEach(x=>x.classList.toggle('active',x===b));render()});$$('[data-range]').forEach(b=>b.onclick=()=>{chartRange=b.dataset.range;$$('[data-range]').forEach(x=>x.classList.toggle('active',x===b));renderChart()});$('#buyingPowerRow').onclick=()=>toast('Buying power is uncommitted paper capital');document.querySelector('.chart-gear')?.addEventListener('click',()=>$('#chartSettings').showModal());
let dragStart=null,dragY=0;$('#sheetHandle').addEventListener('touchstart',e=>{dragStart=e.touches[0].clientY;dragY=0},{passive:true});$('#sheetHandle').addEventListener('touchmove',e=>{if(dragStart===null)return;dragY=Math.max(0,e.touches[0].clientY-dragStart);$('#sheet').style.transform=`translateY(${dragY}px)`},{passive:true});$('#sheetHandle').addEventListener('touchend',()=>{if(dragY>90)closeSheet();else $('#sheet').style.transform='';dragStart=null;dragY=0});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSheet();if(e.key==='Tab'&&$('#sheet').classList.contains('open')){const btns=[...$('#sheet').querySelectorAll('button')],first=btns[0],last=btns.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
$('#mobileSearch').addEventListener('input',renderSearch);$('#accountRefresh').onclick=load;$$('[data-explore]').forEach(b=>b.onclick=()=>{searchCategory=b.dataset.explore;$$('[data-explore]').forEach(x=>x.classList.toggle('active',x===b));renderSearch()});$('#areaFill').onchange=e=>{document.body.classList.toggle('show-area',e.target.checked)};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'}).catch(()=>{}));load();setInterval(load,60000);
